const clean=v=>String(v??'').trim();
const digits=v=>clean(v).replace(/\D/g,'');
const iso=v=>/^\d{4}-\d{2}-\d{2}$/.test(clean(v));
const round2=n=>Math.round((Number(n)+Number.EPSILON)*100)/100;
const json=(status,data)=>({statusCode:status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'},body:JSON.stringify(data)});
async function getText(url,opts={},timeout=12000){const ac=new AbortController();const t=setTimeout(()=>ac.abort(),timeout);try{const r=await fetch(url,{...opts,signal:ac.signal,headers:{'User-Agent':'KSeF-Checker-Work-Online/2.6',...(opts.headers||{})}});const text=await r.text();return{ok:r.ok,status:r.status,text,headers:r.headers}}finally{clearTimeout(t)}}
async function getJson(url,opts={}){const r=await getText(url,{...opts,headers:{Accept:'application/json',...(opts.headers||{})}});let j=null;try{j=JSON.parse(r.text)}catch{}if(!r.ok)throw new Error(j?.message||j?.exception?.message||`HTTP ${r.status}`);return j}
function dateShift(s,n){const d=new Date(`${s}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
async function whiteListSearch(nip,date){if(!/^\d{10}$/.test(nip)||!iso(date))throw new Error('Nieprawidłowy NIP lub data.');const j=await getJson(`https://wl-api.mf.gov.pl/api/search/nip/${encodeURIComponent(nip)}?date=${encodeURIComponent(date)}`);return{subject:j?.result?.subject||j?.result?.subjects?.[0]||null,requestId:j?.result?.requestId||'',requestDateTime:j?.result?.requestDateTime||''}}
async function whiteListBank(nip,account,date){account=digits(account);if(!/^\d{10}$/.test(nip)||!/^\d{26}$/.test(account)||!iso(date))throw new Error('Nieprawidłowy NIP, rachunek lub data.');const j=await getJson(`https://wl-api.mf.gov.pl/api/check/nip/${encodeURIComponent(nip)}/bank-account/${encodeURIComponent(account)}?date=${encodeURIComponent(date)}`);return{assigned:clean(j?.result?.accountAssigned),requestId:j?.result?.requestId||'',requestDateTime:j?.result?.requestDateTime||''}}
function xmlTag(xml,tag){const m=xml.match(new RegExp(`<(?:\\w+:)?${tag}[^>]*>([\\s\\S]*?)<\\/(?:\\w+:)?${tag}>`,'i'));return m?m[1].replace(/<[^>]+>/g,'').trim():''}
async function viesCheck(code,vat){code=clean(code).toUpperCase();if(code==='GR')code='EL';vat=clean(vat).replace(/[\s.\-]/g,'').replace(new RegExp(`^${code}`,'i'),'');if(!code||!vat)throw new Error('Nieprawidłowy VAT UE.');const body=`<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:ec.europa.eu:taxud:vies:services:checkVat:types"><soapenv:Header/><soapenv:Body><urn:checkVat><urn:countryCode>${code}</urn:countryCode><urn:vatNumber>${vat}</urn:vatNumber></urn:checkVat></soapenv:Body></soapenv:Envelope>`;const r=await getText('https://ec.europa.eu/taxation_customs/vies/services/checkVatService',{method:'POST',headers:{'Content-Type':'text/xml; charset=utf-8','SOAPAction':'""'},body});if(!r.ok)throw new Error(`VIES HTTP ${r.status}`);const fault=xmlTag(r.text,'faultstring');if(fault)throw new Error(`VIES: ${fault}`);const v=xmlTag(r.text,'valid');if(!v)throw new Error('VIES zwrócił odpowiedź bez pola valid');return{countryCode:code,vatNumber:vat,valid:v.toLowerCase()==='true',name:xmlTag(r.text,'name'),address:xmlTag(r.text,'address'),requestDate:xmlTag(r.text,'requestDate')}}
async function nbpRate(currency,referenceDate){currency=clean(currency).toUpperCase();if(currency==='PLN'||!/^[A-Z]{3}$/.test(currency)||!iso(referenceDate))throw new Error('Nieprawidłowa waluta lub data.');const end=dateShift(referenceDate,-1),start=dateShift(referenceDate,-14);for(const table of ['a','b']){try{const j=await getJson(`https://api.nbp.pl/api/exchangerates/rates/${table}/${currency.toLowerCase()}/${start}/${end}/?format=json`),rates=Array.isArray(j?.rates)?j.rates:[];if(rates.length){const x=rates[rates.length-1];return{currency,table:table.toUpperCase(),date:x.effectiveDate,mid:Number(x.mid),no:x.no||'',manualUrl:'https://nbp.pl/statystyka-i-sprawozdawczosc/kursy/'}}}catch(e){if(!/404/.test(String(e.message)))throw e}}throw new Error(`NBP nie zwrócił kursu ${currency} przed ${referenceDate}`)}
function partyVatId(p){const cc=clean(p?.kodUE||p?.country||p?.countryId).toUpperCase(),nr=clean(p?.vatUE);if(cc&&nr)return{code:cc,vat:nr};const nip=digits(p?.nip);if(nip.length===10&&(!cc||cc==='PL'))return{code:'PL',vat:nip};return null}
function add(checks,type,category,title,desc,field='',fix=''){checks.push({type,category,title,desc,field,fix})}
async function audit(payload){const checks=[],details={seller:{},buyer:{},bankAccounts:[],registryDate:''};let unavailable=0;const date=iso(payload.invoiceDate)?payload.invoiceDate:new Date().toISOString().slice(0,10);details.registryDate=date;const seller={...(payload.seller||{}),nip:digits(payload.seller?.nip)},buyer={...(payload.buyer||{}),nip:digits(payload.buyer?.nip)},domesticVat=!!payload.domesticVat,importantVies=!!(payload.flags?.wdt||payload.flags?.reverse);for(const [key,label,p] of [['seller','sprzedawca',seller],['buyer','nabywca',buyer]]){if(/^\d{10}$/.test(p.nip)){try{const r=await whiteListSearch(p.nip,date),s=r.subject;details[key].mf=s?{found:true,name:s.name||'',statusVat:s.statusVat||'',residenceAddress:s.residenceAddress||'',workingAddress:s.workingAddress||'',accountNumbers:s.accountNumbers||[],requestId:r.requestId}:{found:false,requestId:r.requestId};add(checks,s&&String(s.statusVat).toLowerCase()==='czynny'?'ok':domesticVat?'warn':'info','registry',`Biała Lista MF — ${label}`,s?`NIP ${p.nip}: status VAT „${s.statusVat||'brak'}”.${r.requestId?` Id zapytania MF: ${r.requestId}.`:''}`:`Nie znaleziono podmiotu dla NIP ${p.nip}.`,`NIP ${p.nip}`,s?'':'Zweryfikuj NIP i datę sprawdzenia.')}catch(e){unavailable++;add(checks,'info','registry',`Biała Lista MF — ${label}`,`Nie udało się pobrać statusu: ${e.message}.`,`NIP ${p.nip}`,'Spróbuj ponownie.')}}else add(checks,'info','registry',`Biała Lista MF — ${label}`,'Brak poprawnego polskiego NIP — kontrola pominięta.');const id=partyVatId(p);if(id){try{const v=await viesCheck(id.code,id.vat);details[key].vies=v;add(checks,v.valid?'ok':importantVies?'warn':'info','registry',`VIES / VAT UE — ${label}`,`${v.countryCode}${v.vatNumber}: ${v.valid?'numer aktywny':'numer nieaktywny'} w VIES.`,`${v.countryCode}${v.vatNumber}`,v.valid?'':'Sprawdź status VAT UE.')}catch(e){unavailable++;add(checks,'info','registry',`VIES / VAT UE — ${label}`,`Weryfikacja VIES niedostępna: ${e.message}.`)}}
}
const accountDate=iso(payload.paidDate)?payload.paidDate:date;if(Array.isArray(payload.banks)&&payload.banks.length&&/^\d{10}$/.test(seller.nip)){for(const raw of payload.banks){const acc=digits(raw);if(!/^\d{26}$/.test(acc)){add(checks,'warn','registry','Rachunek bankowy — format',`Rachunek „${raw}” nie ma 26 cyfr.`);continue}try{const r=await whiteListBank(seller.nip,acc,accountDate),yes=clean(r.assigned).toUpperCase()==='TAK';details.bankAccounts.push({account:acc,assigned:yes,date:accountDate,requestId:r.requestId});add(checks,yes?'ok':'warn','registry','Rachunek bankowy na Białej Liście',`${acc}: ${yes?'rachunek przypisany':'rachunek NIEpotwierdzony'} do NIP sprzedawcy na dzień ${accountDate}.`,'Fa/Platnosc/RachunekBankowy/NrRB',yes?'':'Sprawdź rachunek przed płatnością.')}catch(e){unavailable++;add(checks,'info','registry','Rachunek bankowy na Białej Liście',`Nie udało się zweryfikować rachunku: ${e.message}.`)}}}
const currency=clean(payload.currency).toUpperCase();if(currency&&currency!=='PLN'&&domesticVat&&!payload.flags?.correction){const ref=iso(payload.saleDate)?payload.saleDate:iso(payload.invoiceDate)?payload.invoiceDate:'';if(ref){try{const r=await nbpRate(currency,ref);add(checks,'ok','fx','Kurs NBP — kurs referencyjny',`${currency}: średni kurs NBP ${r.mid.toFixed(4)} z ${r.date}, tabela ${r.table}${r.no?` ${r.no}`:''}.`,'Fa/KodWaluty');for(const g of Array.isArray(payload.vatGroups)?payload.vatGroups:[]){const foreign=Number(String(g.foreignVat||'').replace(',','.')),pln=Number(String(g.plnVat||'').replace(',','.'));if(!(foreign&&Number.isFinite(pln)))continue;const expected=round2(foreign*r.mid),diff=round2(pln-expected);add(checks,Math.abs(diff)<=.02?'ok':'warn','fx',`Kurs NBP — ${g.label}`,`VAT ${foreign.toFixed(2)} ${currency}; P_14_*W ${pln.toFixed(2)} PLN; wg kursu ≈ ${expected.toFixed(2)} PLN; różnica ${diff.toFixed(2)} PLN.`)}}catch(e){unavailable++;add(checks,'info','fx','Kurs NBP',`Nie udało się pobrać kursu: ${e.message}.`)}}}
return{checks,unavailable,details,checkedAt:new Date().toISOString(),registryDate:date}}

const TAX_RATE=[{from:'2022-02-09',rate:8.5},{from:'2022-03-09',rate:10},{from:'2022-04-07',rate:12},{from:'2022-05-06',rate:13.5},{from:'2022-06-09',rate:15},{from:'2022-07-08',rate:16},{from:'2022-09-08',rate:16.5},{from:'2023-09-07',rate:15},{from:'2023-10-05',rate:14.5},{from:'2025-05-08',rate:13.5},{from:'2025-07-03',rate:13},{from:'2025-09-04',rate:12.5},{from:'2025-10-09',rate:12},{from:'2025-11-06',rate:11.5},{from:'2025-12-04',rate:11},{from:'2026-03-05',rate:10.5}];
const TRADE=[{from:'2025-07-01',to:'2025-12-31',standard:15.25,medical:13.25,sourceName:'M.P. 2025 poz. 602',sourceUrl:'https://eli.gov.pl/eli/MP/2025/602/ogl'},{from:'2026-01-01',to:'2026-06-30',standard:14,medical:12,sourceName:'M.P. 2025 poz. 1257',sourceUrl:'https://eli.gov.pl/eli/MP/2025/1257/ogl'},{from:'2026-07-01',to:'2026-12-31',standard:13.75,medical:11.75,sourceName:'M.P. 2026 poz. 642',sourceUrl:'https://eli.gov.pl/eli/MP/2026/642/ogl'}];
function dObj(s){return new Date(`${s}T00:00:00Z`)} function days(a,b){return Math.floor((dObj(b)-dObj(a))/86400000)+1} function addDay(s,n){const d=dObj(s);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
async function interest(type,amount,due,paid){amount=Number(amount);if(!Number.isFinite(amount)||amount<=0||!iso(due)||!iso(paid))throw new Error('Nieprawidłowa kwota lub data.');if(paid<=due)return{type,days:0,interest:0,total:round2(amount),segments:[],liveVerified:true,note:'Data zapłaty nie jest późniejsza niż termin płatności.'};const start=addDay(due,1),end=paid,isTax=String(type).startsWith('tax'),segments=[];if(isTax){const factor=type==='taxReduced'?.5:type==='taxIncreased'?1.5:1,cuts=[start,...TAX_RATE.map(x=>x.from).filter(x=>x>start&&x<=end)].sort();for(let i=0;i<cuts.length;i++){const from=cuts[i],to=i+1<cuts.length?addDay(cuts[i+1],-1):end,x=[...TAX_RATE].reverse().find(z=>z.from<=from);if(x)segments.push({from,to,days:days(from,to),rate:round2(x.rate*factor),sourceName:'ZUS / stawki odsetek',sourceUrl:'https://www.zus.pl/en/baza-wiedzy/skladki-wskazniki-odsetki/odsetki/wysokosc-stawek-odsetek-podatkowych-za-zwloke-od-nieterminowo-regulowanych-skladek-na-ubezpieczenia-spoleczne'})}}else{const med=type==='tradeMedical',cuts=[start,...TRADE.map(x=>x.from).filter(x=>x>start&&x<=end)].sort();for(let i=0;i<cuts.length;i++){const from=cuts[i],to=i+1<cuts.length?addDay(cuts[i+1],-1):end,x=TRADE.find(z=>z.from<=from&&z.to>=from);if(!x)throw new Error('Brak stawki dla wskazanego okresu.');segments.push({from,to,days:days(from,to),rate:med?x.medical:x.standard,sourceName:x.sourceName,sourceUrl:x.sourceUrl})}}let raw=0;for(const x of segments){x.interest=round2(amount*x.rate/100*x.days/365);raw+=amount*x.rate/100*x.days/365}const val=isTax?Math.round(raw):round2(raw);let liveVerified=false;try{const urls=[...new Set(segments.map(x=>x.sourceUrl).filter(Boolean))];const checks=await Promise.all(urls.map(u=>getText(u,{},5000)));liveVerified=checks.every(r=>r.ok)}catch{}return{type,days:days(start,end),interest:val,total:round2(amount+val),segments,liveVerified,note:liveVerified?'Źródła stawek są dostępne online.':'Obliczenie na wbudowanych stawkach; nie udało się potwierdzić wszystkich źródeł online.'}}

const SOURCES=[['fa3','KSeF / FA(3)','https://ksef.podatki.gov.pl/informacje-ogolne-ksef-20/struktura-logiczna-fa-3/'],['scale','podatki.gov.pl / stawki','https://www.podatki.gov.pl/podatki-firmowe/pit/stawki-i-limity'],['health','ZUS / zdrowotna','https://www.zus.pl/pl/firmy/przedsiebiorco-przeczytaj-wazne/kalkulator-skladki-zdrowotnej'],['mpp','podatki.gov.pl / MPP','https://www.podatki.gov.pl/podatki-firmowe/vat/poradniki-i-informatory/mechanizm-podzielonej-platnosci-mpp'],['nbp','NBP API','https://api.nbp.pl/'],['wl','Biała Lista MF API','https://wl-api.mf.gov.pl/'],['vies','VIES','https://ec.europa.eu/taxation_customs/vies/']];
async function legalStatus(){const sources=await Promise.all(SOURCES.map(async([id,name,url])=>{try{const r=await getText(url,{method:'GET'},7000);return{id,name,url,ok:r.ok,status:r.status,error:r.ok?'':`HTTP ${r.status}`}}catch(e){return{id,name,url,ok:false,status:0,error:e.message}}}));return{checkedAt:new Date().toISOString(),sources}}
const XSD=[['schemat_FA(3)_v1-0E.xsd','https://crd.gov.pl/wzor/2025/06/25/13775/schemat.xsd'],['StrukturyDanych_v10-0E.xsd','https://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/StrukturyDanych_v10-0E.xsd'],['ElementarneTypyDanych_v10-0E.xsd','https://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/ElementarneTypyDanych_v10-0E.xsd'],['KodyKrajow_v10-0E.xsd','https://crd.gov.pl/xml/schematy/dziedzinowe/mf/2022/01/05/eD/DefinicjeTypy/KodyKrajow_v10-0E.xsd']];
async function xsdStatus(){const files=await Promise.all(XSD.map(async([name,url])=>{try{const r=await getText(url,{},9000);return{name,url,ok:r.ok,status:r.status,size:r.text.length,error:r.ok?'':`HTTP ${r.status}`}}catch(e){return{name,url,ok:false,status:0,size:0,error:e.message}}}));return{available:files[0]?.ok===true,mode:'serverless-online',checkedAt:new Date().toISOString(),files,message:files[0]?.ok?'Oficjalny schemat FA(3) jest dostępny online. Pełna walidacja XSD pozostaje lokalna/serwerowa.':'Nie udało się pobrać oficjalnego schematu FA(3).'}}
const NEWS_SOURCES=[
 {id:'mf',name:'Ministerstwo Finansów',url:'https://www.gov.pl/web/finanse/wiadomosci',official:true,hints:['/web/finanse/']},
 {id:'podatki-gov',name:'podatki.gov.pl',url:'https://podatki.gov.pl/aktualnosci',official:true,hints:['/aktualnosci']},
 {id:'zus',name:'ZUS',url:'https://www.zus.pl/o-zus/aktualnosci',official:true,hints:['/o-zus/aktualnosci','/firmy/','/baza-wiedzy/','/-/']},
 {id:'prawo',name:'Prawo.pl',url:'https://www.prawo.pl/podatki/',official:false,hints:['/podatki/']},
 {id:'infor',name:'INFOR Księgowość',url:'https://ksiegowosc.infor.pl/',official:false,hints:['/podatki/','/ksiegowosc/','/rachunkowosc/']},
 {id:'poradnik',name:'Poradnik Przedsiębiorcy',url:'https://poradnikprzedsiebiorcy.pl/podatki',official:false,hints:['poradnikprzedsiebiorcy.pl/']},
 {id:'gofin',name:'GOFIN',url:'https://news.gofin.pl/',official:false,hints:['gofin.pl/']},
 {id:'pit',name:'PIT.pl',url:'https://www.pit.pl/aktualnosci/',official:false,hints:['/aktualnosci/']}
];
function hdecode(v){return String(v||'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCharCode(parseInt(n,16)))}
function stripHtml(v){return hdecode(String(v||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim())}
function absUrl(raw,base){try{return new URL(hdecode(raw),base).href}catch{return''}}
function isoNewsDate(v){v=clean(v);if(!v)return'';let m=v.match(/(20\d{2})[-/.](\d{1,2})[-/.](\d{1,2})/);if(m)return `${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;m=v.match(/(\d{1,2})[.\-/](\d{1,2})[.\-/](20\d{2})/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;return''}
function relevantNews(v){return /(podat|vat|pit|cit|ksef|jpk|rachunk|księg|zus|składk|faktur|akcyz|cło|sprawozd|ryczałt|ordynac|darowizn|nieruchomo|esrs|audyt|płac|kadrow)/i.test(v)}
function topicNews(v,sourceId){v=String(v||'').toLowerCase();if(sourceId==='zus'||/zus|składk|ubezpieczen/.test(v))return'ZUS';if(/ksef|faktur|vat|jpk|mpp|split payment/.test(v))return'VAT / KSeF';if(/\bpit\b|\bcit\b|ryczałt|dochodo|fundacj.*rodzinn|ip box/.test(v))return'PIT / CIT';if(/rachunk|sprawozd|bilans|księg|esrs|audyt/.test(v))return'Rachunkowość';if(/kadrow|wynagrod|prawo pracy|pracown|urlop|zasiłk/.test(v))return'Kadry i płace';return'Podatki i prawo'}
function plannedNews(v){return /projekt|planowan|propozyc|konsultac|od 2027|od 2028|ma się zmienić|zmiany w .* od/i.test(String(v||''))}
function sourceUrlOk(url,source){try{const u=new URL(url),b=new URL(source.url),uh=u.hostname.replace(/^www\./,''),bh=b.hostname.replace(/^www\./,'');if(!(uh===bh||uh.endsWith('.'+bh)||bh.endsWith('.'+uh)))return false;if(u.href===source.url||u.pathname==='/'||/\.(jpg|jpeg|png|gif|svg|pdf|zip)$/i.test(u.pathname))return false;return source.hints.some(h=>u.href.includes(h))}catch{return false}}
function newsCandidates(html,source){const out=[],seen=new Set();const re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))){const title=stripHtml(m[2]),url=absUrl(m[1],source.url);if(title.length<28||title.length>240||!sourceUrlOk(url,source)||!relevantNews(title+' '+url))continue;const key=url.replace(/[?#].*$/,'');if(seen.has(key))continue;seen.add(key);const ctx=stripHtml(html.slice(Math.max(0,m.index-340),Math.min(html.length,re.lastIndex+620)));const dm=ctx.match(/(20\d{2}[-/.]\d{1,2}[-/.]\d{1,2}|\d{1,2}[.\-/]\d{1,2}[.\-/]20\d{2})/);const date=dm?isoNewsDate(dm[1]):'';let summary=ctx.replace(title,' ').replace(/\s+/g,' ').trim();if(summary.length>260)summary=summary.slice(0,257).replace(/\s+\S*$/,'')+'…';if(summary.length<35)summary='';out.push({title,summary,url,date,source:source.name,sourceId:source.id,official:source.official,topic:topicNews(title+' '+summary,source.id),planned:plannedNews(title+' '+summary)});if(out.length>=7)break}return out}
async function harvestNewsSource(source){const r=await getText(source.url,{headers:{Accept:'text/html,application/xhtml+xml','Accept-Language':'pl-PL,pl;q=0.9'}},5500);if(!r.ok)throw new Error(`HTTP ${r.status}`);const articles=newsCandidates(r.text.slice(0,3_000_000),source);return{source,articles}}
function dedupeNews(list){const seenU=new Set(),seenT=new Set(),out=[];for(const a of list){const u=String(a.url||'').replace(/[?#].*$/,''),t=String(a.title||'').toLowerCase().replace(/\s+/g,' ').trim();if(!u||!t||seenU.has(u)||seenT.has(t))continue;seenU.add(u);seenT.add(t);out.push(a)}return out.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))}
async function news(){
 const settled=await Promise.all(NEWS_SOURCES.map(async source=>{try{return{ok:true,...await harvestNewsSource(source)}}catch(e){return{ok:false,source,articles:[],error:e?.message||String(e)}}}));
 const statuses=[],fresh=[];for(const r of settled){fresh.push(...r.articles);statuses.push({id:r.source.id,name:r.source.name,ok:r.ok&&r.articles.length>0,count:r.articles.length,error:r.ok&&!r.articles.length?'Brak dopasowanych materiałów na stronie źródłowej.':r.error||''})}
 const articles=dedupeNews(fresh).slice(0,45);return{version:'2.6.3-WORK-ONLINE',updatedAt:new Date().toISOString(),articles,sources:statuses,freshSources:statuses.filter(x=>x.ok).length,fallback:false,partial:statuses.some(x=>!x.ok)}
}
function resolveRoute(event){
 const q=event?.queryStringParameters||{};
 if(q.route)return String(q.route).replace(/^\/+|\/+$/g,'');
 const candidates=[event?.path,event?.rawUrl];
 for(const raw of candidates){
  if(!raw)continue;
  let p=String(raw);
  try{if(/^https?:/i.test(p))p=new URL(p).pathname}catch{}
  p=p.split('?')[0];
  for(const prefix of ['/.netlify/functions/api/','/api/']){
   const i=p.indexOf(prefix);if(i>=0){const r=p.slice(i+prefix.length).replace(/^\/+|\/+$/g,'');if(r)return r}
  }
 }
 return '';
}
export async function handler(event){if(event.httpMethod==='OPTIONS')return json(204,{});try{const q=event.queryStringParameters||{},route=resolveRoute(event);let body={};if(event.body){try{body=JSON.parse(event.body)}catch{body={}}}
if(route==='toolbox/contractor'){const nip=digits(q.nip),date=q.date||'',r=await whiteListSearch(nip,date),s=r.subject;let vies=null,viesError='';if(q.country&&q.vat){try{vies=await viesCheck(q.country,q.vat)}catch(e){viesError=e.message}}return json(200,{mf:s?{found:true,name:s.name||'',statusVat:s.statusVat||'',residenceAddress:s.residenceAddress||'',workingAddress:s.workingAddress||'',accountNumbers:s.accountNumbers||[],krs:s.krs||'',regon:s.regon||'',registrationLegalDate:s.registrationLegalDate||'',hasVirtualAccounts:!!s.hasVirtualAccounts}:{found:false,accountNumbers:[]},vies,viesError,requestId:r.requestId,requestDateTime:r.requestDateTime,date})}
if(route==='toolbox/bank'){const r=await whiteListBank(digits(q.nip),digits(q.account),q.date||'');return json(200,{assigned:clean(r.assigned).toUpperCase()==='TAK',requestId:r.requestId,requestDateTime:r.requestDateTime,nip:digits(q.nip),account:digits(q.account),date:q.date||''})}
if(route==='toolbox/vies')return json(200,await viesCheck(q.country||'',q.vat||''));
if(route==='toolbox/nbp')return json(200,await nbpRate(q.currency||'',q.date||''));
if(route==='toolbox/interest')return json(200,await interest(q.type||'',q.amount||'',q.due||'',q.paid||''));
if(route==='audit')return json(200,await audit(body));
if(route==='legal/status')return json(200,await legalStatus());
if(route==='xsd/status'||route==='xsd/sync')return json(200,await xsdStatus());
if(route==='xsd/validate')return json(200,{available:false,ok:null,engine:'serverless-online',errors:[{message:'Schemat FA(3) jest sprawdzany online, ale pełna walidacja XSD nie jest wykonywana w tej lekkiej funkcji serverless.'}]});
if(route==='news')return json(200,await news());
if(route==='health')return json(200,{ok:true,version:'2.6.3-WORK-ONLINE',serverless:true,time:new Date().toISOString()});
if(route==='qa/server')return json(200,{version:'2.6.3-WORK-ONLINE',platform:'Netlify Functions',serverless:true,time:new Date().toISOString(),xsd:await xsdStatus()});
return json(404,{error:`Nieznana trasa API: ${route}`});}catch(e){return json(503,{error:e?.message||String(e)})}}
