(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const CLIENTS_KEY='ksefChecker.clients.v1', ACTIVE_KEY='ksefChecker.clients.active.v1', HISTORY_KEY='ksef-checker-pro-history-v2';
const HEALTH_KEY='ksefChecker.healthClients.v1', HEALTH_ACTIVE='ksefChecker.healthActive.v1';
const LEGAL_STATUS_KEY='ksefChecker.legalStatus.v1', REGISTRY_CACHE_KEY='ksefChecker.registryCache.v1';
const nowIso=()=>new Date().toISOString();
const money=n=>new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
const num=v=>{const n=Number(String(v??'').replace(/[\s\u00A0\u202F]/g,'').replace(',','.'));return Number.isFinite(n)?n:0};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtForm=f=>f==='linear'?'Podatek liniowy':f==='ryc'?'Ryczałt':'Skala podatkowa';
const safeJson=(key,fb)=>{try{const x=JSON.parse(localStorage.getItem(key)||'');return x??fb}catch{return fb}};
const saveJson=(key,v)=>{try{localStorage.setItem(key,JSON.stringify(v));return true}catch{return false}};
const uid=p=>`${p}_${Date.now()}_${Math.random().toString(36).slice(2,7)}`;
let clients=[],activeId='',saveTimer=null,registryFetchTimer=null,registryBusy=false;

const RULES=[
 {id:'fa3',title:'Struktura logiczna FA(3)',area:'KSeF',status:'current',from:'2026-02-01',verified:'2026-09-28',summary:'FA(3) zastąpiła FA(2) dla faktur ustrukturyzowanych od 1 lutego 2026 r.',source:'https://ksef.podatki.gov.pl/informacje-ogolne-ksef-20/struktura-logiczna-fa-3/',sourceName:'KSeF / MF'},
 {id:'scale',title:'Skala PIT 12% / 32%',area:'PIT',status:'current',from:'2026-01-01',verified:'2026-09-28',summary:'12% do 120 000 zł minus 3 600 zł; 32% od nadwyżki ponad 120 000 zł.',source:'https://www.podatki.gov.pl/podatki-firmowe/pit/stawki-i-limity',sourceName:'podatki.gov.pl'},
 {id:'linear',title:'Podatek liniowy 19%',area:'PIT',status:'current',from:'2026-01-01',verified:'2026-09-28',summary:'Stawka liniowa działalności gospodarczej wynosi 19%, z odrębnymi zasadami zdrowotnej i odliczeń.',source:'https://www.podatki.gov.pl/podatki-firmowe/pit/informacje-podstawowe/co-jest-opodatkowane/opodatkowanie-podatkiem-liniowym',sourceName:'podatki.gov.pl'},
 {id:'health',title:'Składka zdrowotna przedsiębiorców 2026',area:'ZUS',status:'current',from:'2026-01-01',verified:'2026-09-28',summary:'Skala 9%, liniowy 4,9%, minima oraz progi ryczałtu zgodnie z parametrami ZUS 2026.',source:'https://www.zus.pl/pl/firmy/przedsiebiorco-przeczytaj-wazne/kalkulator-skladki-zdrowotnej',sourceName:'ZUS'},
 {id:'assetHealth',title:'Sprzedaż ŚT a zdrowotna',area:'ZUS',status:'current',from:'2025-01-01',verified:'2026-09-28',summary:'Sprzedaż ŚT/WNiP jest wyłączona z miesięcznej podstawy; dla skali/liniowego może być uwzględniona w rozliczeniu rocznym według aktualnych zasad ZUS.',source:'https://www.zus.pl/en/-/od-1-maja-2026-r.-obowi%C4%85zuj%C4%85-nowe-wzory-formularzy-zus-dra-i-zus-rca',sourceName:'ZUS'},
 {id:'mpp',title:'Obowiązkowy MPP',area:'VAT',status:'current',from:'2026-01-01',verified:'2026-09-28',summary:'Ocena progu 15 000 zł i pozycji z załącznika nr 15 wymaga spełnienia ustawowych przesłanek.',source:'https://www.podatki.gov.pl/podatki-firmowe/vat/poradniki-i-informatory/mechanizm-podzielonej-platnosci-mpp',sourceName:'podatki.gov.pl'},
 {id:'nbp',title:'Kursy walut NBP',area:'Waluty',status:'current',from:'2025-08-01',verified:'2026-09-28',summary:'NBP udostępnia aktualne i archiwalne kursy przez HTTPS API oraz archiwa tabel.',source:'https://api.nbp.pl/',sourceName:'NBP'},
 {id:'lease',title:'Limity samochodów 2026',area:'KUP',status:'current',from:'2026-01-01',verified:'2026-09-28',summary:'W kalkulatorze leasingu stosowane są limity 100 / 150 / 225 tys. zł zależnie od rodzaju pojazdu.',source:'https://www.podatki.gov.pl/media/rr5pgg25/podatki-2026-przewodnik-dla-inwestorow.pdf',sourceName:'MF'}
];

function blankClient(name='Nowy klient'){return{id:uid('client'),name,nip:'',taxForm:'scale',rycRate:'8.5',vatStatus:'unknown',email:'',bank:'',regon:'',krs:'',address:'',registryAccounts:[],registryCheckedAt:'',registryRequestId:'',healthId:'',taxPaid:0,healthPaid:0,notes:'',assets:[],events:[],createdAt:nowIso(),updatedAt:nowIso()}}
function normalizeClient(c){return{...blankClient(c?.name||'Klient'),...c,assets:Array.isArray(c?.assets)?c.assets:[],events:Array.isArray(c?.events)?c.events:[]}}
function load(){clients=safeJson(CLIENTS_KEY,[]).map(normalizeClient);syncFromHealth();if(!clients.length)clients=[blankClient('Klient 1')];activeId=localStorage.getItem(ACTIVE_KEY)||clients[0].id;if(!clients.some(x=>x.id===activeId))activeId=clients[0].id;save(false)}
function syncFromHealth(){const h=safeJson(HEALTH_KEY,[]);for(const hc of h){let c=clients.find(x=>x.healthId===hc.id)||clients.find(x=>x.name&&hc.name&&x.name.toLowerCase()===hc.name.toLowerCase());if(!c){c=blankClient(hc.name||'Klient');c.healthId=hc.id;c.taxForm=hc.form||'scale';clients.push(c)}else if(!c.healthId)c.healthId=hc.id}}
function save(show=true){saveJson(CLIENTS_KEY,clients);localStorage.setItem(ACTIVE_KEY,activeId);if(show){const el=$('#clientSaveState');if(el){el.textContent='Zapisano lokalnie';clearTimeout(saveTimer);saveTimer=setTimeout(()=>el.textContent='',1000)}}}
function current(){return clients.find(x=>x.id===activeId)||clients[0]}
function healthClients(){return safeJson(HEALTH_KEY,[])}
function linkedHealth(c=current()){const hs=healthClients();return hs.find(x=>x.id===c?.healthId)||hs.find(x=>x.name&&c?.name&&x.name.toLowerCase()===c.name.toLowerCase())||null}
function history(){return safeJson(HISTORY_KEY,[])}
function clientHistory(c=current()){const nip=String(c?.nip||'').replace(/\D/g,'');if(!nip)return[];return history().filter(x=>String(x.sellerNip||'').replace(/\D/g,'')===nip||String(x.buyerNip||'').replace(/\D/g,'')===nip)}
function formColor(f){return f==='linear'?'purple':f==='ryc'?'green':'blue'}
function scaleTax(base){base=Math.max(0,Math.round(base));if(base<=120000)return Math.max(0,Math.round(base*.12-3600));return Math.round(10800+(base-120000)*.32)}
function monthsWithData(h){if(!h?.months)return[];return h.months.map((m,i)=>({...m,i})).filter(m=>m.active!==false&&[m.revenue,m.costs,m.social,m.incomeDirect,m.assetRevenue,m.assetCost].some(v=>String(v??'').trim()!==''&&num(v)!==0))}
function forecast(c=current()){
 const h=linkedHealth(c), rows=monthsWithData(h);if(!h||!rows.length)return{available:false};
 const n=rows.length, revenue=rows.reduce((s,m)=>s+num(m.revenue),0),costs=rows.reduce((s,m)=>s+num(m.costs),0),social=rows.reduce((s,m)=>s+num(m.social),0);
 const factor=12/n, annualRevenue=revenue*factor,annualCosts=costs*factor,annualSocial=social*factor,income=Math.max(0,annualRevenue-annualCosts-annualSocial);
 let pit=0,health=0;
 if(c.taxForm==='linear'){pit=Math.round(income*.19);health=Math.max(432.54*12,income*.049)}
 else if(c.taxForm==='ryc'){const rate=Math.max(0,num(c.rycRate))/100;const tier=annualRevenue<=60000?498.35:annualRevenue<=300000?830.58:1495.04;health=tier*12;pit=Math.max(0,annualRevenue-annualSocial-health*.5)*rate}
 else{pit=scaleTax(income);health=Math.max(432.54*11+314.96,income*.09)}
 const remainTax=Math.max(0,pit-num(c.taxPaid)),remainHealth=Math.max(0,health-num(c.healthPaid)),remainingMonths=Math.max(1,12-n);
 return{available:true,n,revenue,costs,social,annualRevenue,annualCosts,annualSocial,income,pit,health,remainTax,remainHealth,reserve:(remainTax+remainHealth)/remainingMonths,remainingMonths};
}
function legalStatuses(){return safeJson(LEGAL_STATUS_KEY,{checkedAt:null,sources:[]})}
function todayLocal(){const d=new Date(),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
function nipValid(v){const n=String(v||'').replace(/\D/g,'');if(!/^\d{10}$/.test(n))return false;const w=[6,5,7,2,3,4,5,6,7],r=w.reduce((a,x,i)=>a+x*Number(n[i]),0)%11;return r!==10&&r===Number(n[9])}
function mapVatStatus(s){const v=String(s||'').toLowerCase();if(v.includes('czynny'))return'active';if(v.includes('zwoln'))return'exempt';if(v.includes('niezarejest')||v.includes('wykre')||v.includes('odmow'))return'inactive';return'unknown'}
function registryAddress(mf){return mf?.workingAddress||mf?.residenceAddress||''}
function registryCache(){return safeJson(REGISTRY_CACHE_KEY,{})}
function setRegistryState(kind,title,text=''){const el=$('#clientRegistryState');if(!el)return;el.className=`client-registry-state ${kind||''}`;el.innerHTML=`<div><b>${esc(title)}</b>${text?`<span>${text}</span>`:''}</div>`}
function renderRegistryInfo(c=current()){
 const st=$('#clientRegistryState'),box=$('#clientRegistryAccounts');if(!st||!box||!c)return;
 if(c.registryCheckedAt){const when=new Date(c.registryCheckedAt),label=Number.isNaN(when.getTime())?c.registryCheckedAt:when.toLocaleString('pl-PL',{dateStyle:'short',timeStyle:'short'});setRegistryState('ok','Dane pobrane z Wykazu podatników VAT MF',`Ostatnia weryfikacja: ${esc(label)}${c.registryRequestId?` · ID zapytania: ${esc(c.registryRequestId)}`:''}. Forma opodatkowania, stawka ryczałtu i e-mail nie są dostępne w tym rejestrze — uzupełnij je ręcznie. <a href="https://www.podatki.gov.pl/wykaz-podatnikow-vat-wyszukiwarka/" target="_blank" rel="noopener">Sprawdź w MF ↗</a>`)}
 else{st.className='client-registry-state info';st.innerHTML='<div><b>Automatyczne dane po NIP</b><span>Wpisz poprawny 10-cyfrowy NIP. Checker pobierze nazwę, status VAT, REGON/KRS, adres i dostępne rachunki z oficjalnego Wykazu podatników VAT MF.</span></div>'}
 const acc=Array.isArray(c.registryAccounts)?c.registryAccounts:[];if(!acc.length){box.classList.add('hidden');box.innerHTML='';return}box.classList.remove('hidden');box.innerHTML=`<b>Rachunki z Białej Listy (${acc.length})</b><span>Wybierz rachunek, który chcesz zapisać w kartotece:</span><div class="registry-account-buttons">${acc.map(a=>`<button type="button" class="registry-account-btn ${String(c.bank||'').replace(/\D/g,'')===String(a).replace(/\D/g,'')?'active':''}" data-registry-account="${esc(a)}">${esc(a)}</button>`).join('')}</div>`;box.querySelectorAll('[data-registry-account]').forEach(b=>b.onclick=()=>{const cc=current();if(!cc)return;const old=cc.bank||'';cc.bank=b.dataset.registryAccount||'';$('#clientBank').value=cc.bank;if(old!==cc.bank){cc.events=cc.events||[];cc.events.unshift({at:nowIso(),label:'Rachunek bankowy',from:old,to:cc.bank,source:'Biała Lista MF'})}cc.updatedAt=nowIso();save();renderRegistryInfo(cc);renderClientEvents()})
}
function applyRegistryData(payload,nip,source='online'){
 const c=current(),mf=payload?.mf;if(!c||c.nip!==nip)return false;if(!mf?.found){setRegistryState('warn','Nie znaleziono podmiotu',`Wykaz podatników VAT nie zwrócił danych dla NIP ${esc(nip)} na dzień ${esc(payload?.date||todayLocal())}.`);return false}
 const before={name:c.name,vatStatus:c.vatStatus,bank:c.bank,regon:c.regon,krs:c.krs,address:c.address};
 c.name=mf.name||c.name;c.vatStatus=mapVatStatus(mf.statusVat);c.regon=mf.regon||'';c.krs=mf.krs||'';c.address=registryAddress(mf);c.registryAccounts=Array.isArray(mf.accountNumbers)?mf.accountNumbers:[];if(!c.bank&&c.registryAccounts.length)c.bank=c.registryAccounts[0];c.registryCheckedAt=nowIso();c.registryRequestId=payload.requestId||'';c.updatedAt=nowIso();
 const changed=Object.keys(before).filter(k=>String(before[k]||'')!==String(c[k]||''));if(changed.length){c.events=c.events||[];c.events.unshift({at:nowIso(),label:'Dane rejestrowe z MF',from:'—',to:`Zaktualizowano: ${changed.join(', ')}`,source:'Wykaz podatników VAT'})}
 save(false);renderClient();setRegistryState('ok',source==='cache'?'Dane uzupełnione z pamięci rejestru':'Dane firmy uzupełnione automatycznie',`Źródło: Wykaz podatników VAT MF, stan na ${esc(payload?.date||todayLocal())}. ${mf.statusVat?`Status VAT: ${esc(mf.statusVat)}.`:''}`);return true
}
async function fetchClientRegistry(force=false){
 if(registryBusy)return;const c=current(),input=$('#clientNip');if(!c||!input)return;const nip=String(input.value||'').replace(/\D/g,'').slice(0,10);input.value=nip;if(!nipValid(nip)){if(nip.length===10)setRegistryState('error','Nieprawidłowy NIP','Numer ma 10 cyfr, ale nie przechodzi sumy kontrolnej. Sprawdź wpisane cyfry.');return}
 if(c.nip!==nip){c.nip=nip;c.updatedAt=nowIso();save(false)}const date=todayLocal(),cache=registryCache(),hit=cache[`${nip}|${date}`];if(!force&&hit?.payload){applyRegistryData(hit.payload,nip,'cache');return}
 registryBusy=true;const btn=$('#clientRegistryFetch');if(btn){btn.disabled=true;btn.textContent='Pobieram…'}setRegistryState('loading','Pobieram dane firmy…','Łączę się z oficjalnym API Wykazu podatników VAT Ministerstwa Finansów.');
 try{const r=await fetch(`/api/toolbox/contractor?nip=${encodeURIComponent(nip)}&date=${encodeURIComponent(date)}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);cache[`${nip}|${date}`]={at:nowIso(),payload:j};saveJson(REGISTRY_CACHE_KEY,cache);applyRegistryData(j,nip,'online')}
 catch(e){setRegistryState('error','Nie udało się pobrać danych',`${esc(e.message||e)}. Dane wpisane ręcznie pozostają bez zmian. Możesz spróbować ponownie przyciskiem „Pobierz dane”.`)}
 finally{registryBusy=false;if(btn){btn.disabled=false;btn.textContent='Pobierz dane'}}
}

function renderTabs(){const box=$('#clientTabs');if(!box)return;box.innerHTML=clients.map(c=>`<button class="office-client-tab ${c.id===activeId?'active':''}" data-client-id="${esc(c.id)}"><span>${esc(c.name||'Bez nazwy')}</span><small>${c.nip?`NIP ${esc(c.nip)}`:fmtForm(c.taxForm)}</small></button>`).join('');box.querySelectorAll('[data-client-id]').forEach(b=>b.onclick=()=>{activeId=b.dataset.clientId;save(false);renderClient()})}
function fillHealthOptions(c){const sel=$('#clientHealthLink');if(!sel)return;const hs=healthClients();sel.innerHTML='<option value="">— brak powiązania —</option>'+hs.map(x=>`<option value="${esc(x.id)}">${esc(x.name||'Klient')} · ${esc(fmtForm(x.form))}</option>`).join('');sel.value=c.healthId||''}
function renderClient(){renderTabs();const c=current(),wrap=$('#clientWorkspace'),empty=$('#clientEmpty');if(!c){wrap?.classList.add('hidden');empty?.classList.remove('hidden');return}wrap?.classList.remove('hidden');empty?.classList.add('hidden');
 $('#clientWorkspaceTitle').textContent=c.name||'Klient';$('#clientName').value=c.name||'';$('#clientNip').value=c.nip||'';$('#clientTaxForm').value=c.taxForm||'scale';$('#clientRycRate').value=String(c.rycRate??'8.5').replace('.',',');$('#clientVatStatus').value=c.vatStatus||'unknown';$('#clientRegon').value=c.regon||'';$('#clientKrs').value=c.krs||'';$('#clientAddress').value=c.address||'';$('#clientEmail').value=c.email||'';$('#clientBank').value=c.bank||'';$('#clientTaxPaid').value=c.taxPaid||'';$('#clientHealthPaid').value=c.healthPaid||'';$('#clientNotes').value=c.notes||'';fillHealthOptions(c);renderRegistryInfo(c);renderForecast();renderClientHistory();renderAssets();renderClientEvents();window.numberFormatter?.apply?.($('#clientsView'))}
function bindClientForm(){const c=current();if(!c)return;const before={nip:c.nip,taxForm:c.taxForm,vatStatus:c.vatStatus,bank:c.bank,healthId:c.healthId};c.name=$('#clientName').value.trim()||'Bez nazwy';c.nip=$('#clientNip').value.replace(/\D/g,'').slice(0,10);c.taxForm=$('#clientTaxForm').value;c.rycRate=$('#clientRycRate').value;c.vatStatus=$('#clientVatStatus').value;c.email=$('#clientEmail').value.trim();c.bank=$('#clientBank').value.trim();c.healthId=$('#clientHealthLink').value;c.taxPaid=num($('#clientTaxPaid').value);c.healthPaid=num($('#clientHealthPaid').value);c.notes=$('#clientNotes').value;const labels={nip:'NIP',taxForm:'Forma opodatkowania',vatStatus:'Status VAT',bank:'Rachunek bankowy',healthId:'Powiązanie ze zdrowotną'};for(const k of Object.keys(before)){if(String(before[k]||'')!==String(c[k]||'')){c.events=c.events||[];c.events.unshift({at:nowIso(),field:labels[k],from:String(before[k]||'—'),to:String(c[k]||'—')});c.events=c.events.slice(0,100)}}c.updatedAt=nowIso();save();renderTabs();$('#clientWorkspaceTitle').textContent=c.name;renderForecast();renderClientHistory();renderClientEvents()}
function renderForecast(){const box=$('#clientForecast');if(!box)return;const c=current(),f=forecast(c);if(!f.available){box.innerHTML='<div class="office-empty compact">Powiąż klienta z profilem w kalkulatorze zdrowotnej i uzupełnij co najmniej jeden miesiąc, aby zobaczyć prognozę.</div>';return}box.innerHTML=`<div class="forecast-kpis"><div><span>Przychód YTD (${f.n} mies.)</span><b>${money(f.revenue)}</b></div><div><span>Prognoza przychodu roku</span><b>${money(f.annualRevenue)}</b></div><div><span>Prognoza PIT</span><b>${money(f.pit)}</b></div><div><span>Prognoza zdrowotnej</span><b>${money(f.health)}</b></div><div class="accent"><span>Rezerwa / mies. do końca roku</span><b>${money(f.reserve)}</b></div></div><details class="office-why"><summary>Dlaczego taki wynik?</summary><div>Prognoza annualizuje dane z ${f.n} uzupełnionych miesięcy. Dochód prognozowany: <b>${money(f.annualRevenue)} − ${money(f.annualCosts)} − ${money(f.annualSocial)} = ${money(f.income)}</b>. Od przewidywanego PIT i zdrowotnej odejmowane są wpisane wpłaty YTD. To narzędzie planistyczne — nie zastępuje miesięcznego wyliczenia zaliczki.</div></details>`}
function renderClientHistory(){const box=$('#clientHistory');if(!box)return;const c=current(),hs=clientHistory(c).slice(0,8);if(!c?.nip){box.innerHTML='<div class="office-empty compact">Uzupełnij NIP klienta, aby automatycznie powiązać historię kontroli.</div>';return}if(!hs.length){box.innerHTML='<div class="office-empty compact">Brak kontroli faktur powiązanych po NIP.</div>';return}box.innerHTML=hs.map(x=>`<div class="office-list-row"><span class="office-dot ${x.status}">${x.status==='error'?'×':x.status==='warn'?'!':'✓'}</span><div><b>${esc(x.invoiceNumber||x.fileName||'Faktura')}</b><small>${new Date(x.at).toLocaleDateString('pl-PL')} · ${x.errors||0} bł. / ${x.warns||0} ostrz.</small></div></div>`).join('')}
function renderClientEvents(){const box=$('#clientEvents');if(!box)return;const ev=current()?.events||[];box.innerHTML=ev.length?ev.slice(0,20).map(x=>`<div class="office-list-row"><span class="office-dot info">i</span><div><b>${esc(x.field)}</b><small>${new Date(x.at).toLocaleString('pl-PL')} · ${esc(x.from)} → ${esc(x.to)}</small></div></div>`).join(''):'<div class="office-empty compact">Brak zapisanych zmian w kartotece.</div>'}
function assetResult(a){const init=num(a.initial),dep=Math.min(init,num(a.depreciated)),remaining=Math.max(0,init-dep),sale=num(a.salePrice);return{remaining,result:sale? sale-remaining:null}}
function renderAssets(){const t=$('#assetTable');if(!t)return;const c=current(),as=c?.assets||[];t.innerHTML=`<thead><tr><th>Nazwa</th><th>Data nabycia</th><th>Wartość pocz.</th><th>Umorzenie</th><th>Niezamortyzowana</th><th>Sprzedaż</th><th>Wynik pomocniczy</th><th></th></tr></thead><tbody>${as.map((a,i)=>{const r=assetResult(a);return`<tr><td><input data-asset-i="${i}" data-asset-k="name" value="${esc(a.name||'')}"></td><td><input type="date" data-asset-i="${i}" data-asset-k="purchaseDate" value="${esc(a.purchaseDate||'')}"></td><td><input data-money data-asset-i="${i}" data-asset-k="initial" value="${esc(a.initial||'')}"></td><td><input data-money data-asset-i="${i}" data-asset-k="depreciated" value="${esc(a.depreciated||'')}"></td><td class="locked">${money(r.remaining)}</td><td><input data-money data-asset-i="${i}" data-asset-k="salePrice" value="${esc(a.salePrice||'')}"></td><td class="locked ${r.result!=null&&r.result<0?'negative':''}">${r.result==null?'—':money(r.result)}</td><td><button class="asset-remove" data-asset-remove="${i}">×</button></td></tr>`}).join('')||'<tr><td colspan="8" class="office-empty compact">Brak środków trwałych.</td></tr>'}</tbody>`;t.querySelectorAll('[data-asset-k]').forEach(inp=>inp.onchange=e=>{const i=Number(e.target.dataset.assetI),k=e.target.dataset.assetK;c.assets[i][k]=e.target.value;c.updatedAt=nowIso();save();renderAssets()});t.querySelectorAll('[data-asset-remove]').forEach(b=>b.onclick=()=>{c.assets.splice(Number(b.dataset.assetRemove),1);save();renderAssets()});window.numberFormatter?.apply?.(t)}
function addAsset(){const c=current();if(!c)return;c.assets.push({id:uid('asset'),name:'Nowy środek trwały',purchaseDate:'',initial:'',depreciated:'',salePrice:''});save();renderAssets()}

function renderDashboard(){const k=$('#dashboardKpis'),alerts=$('#dashboardAlerts'),cl=$('#dashboardClients'),leg=$('#dashboardLegal');if(!k)return;const h=history(),recent=h.filter(x=>Date.now()-Date.parse(x.at)<30*864e5),errors=recent.filter(x=>x.status==='error'),hs=healthClients();let healthDue=0;for(const hc of hs){try{const mc=window.healthCalc?.monthlyCalc(hc),a=window.healthCalc?.annualCalc(hc,mc);if(a?.diff>0.01)healthDue++}catch{}}const assets=clients.reduce((s,c)=>s+(c.assets?.length||0),0);k.innerHTML=`<div class="office-kpi"><span>Klienci</span><b>${clients.length}</b><small>${clients.filter(x=>x.nip).length} z NIP</small></div><div class="office-kpi"><span>Kontrole 30 dni</span><b>${recent.length}</b><small>${errors.length} z błędem</small></div><div class="office-kpi"><span>Dopłata zdrowotnej</span><b>${healthDue}</b><small>profile z dodatnią różnicą</small></div><div class="office-kpi"><span>Środki trwałe</span><b>${assets}</b><small>w kartotekach</small></div>`;
 const al=[];errors.slice(0,5).forEach(x=>al.push({kind:'error',title:x.invoiceNumber||x.fileName,text:`${x.errors} błędów · ${x.seller||'—'} → ${x.buyer||'—'}`}));for(const c of clients.filter(x=>!x.nip).slice(0,3))al.push({kind:'warn',title:c.name,text:'Brak NIP w kartotece klienta.'});alerts.innerHTML=al.length?al.map(x=>`<div class="office-list-row"><span class="office-dot ${x.kind}">${x.kind==='error'?'×':'!'}</span><div><b>${esc(x.title)}</b><small>${esc(x.text)}</small></div></div>`).join(''):'<div class="office-empty compact">Brak pilnych alertów.</div>';
 cl.innerHTML=clients.slice(0,7).map(c=>{const count=clientHistory(c).length;return`<button class="office-client-summary" data-dash-client="${esc(c.id)}"><span class="form-pill ${formColor(c.taxForm)}">${esc(fmtForm(c.taxForm))}</span><b>${esc(c.name)}</b><small>${c.nip?`NIP ${esc(c.nip)} · `:''}${count} kontroli</small></button>`}).join('');cl.querySelectorAll('[data-dash-client]').forEach(b=>b.onclick=()=>{activeId=b.dataset.dashClient;save(false);renderClient();showView('clients')});
 const ls=legalStatuses();leg.innerHTML=`<div class="office-list-row"><span class="office-dot ${ls.checkedAt?'ok':'warn'}">${ls.checkedAt?'✓':'!'}</span><div><b>${ls.checkedAt?'Źródła sprawdzone':'Źródła nie były jeszcze sprawdzane'}</b><small>${ls.checkedAt?new Date(ls.checkedAt).toLocaleString('pl-PL'):'Otwórz „Reguły i źródła” i uruchom kontrolę dostępności.'}</small></div></div><div class="office-list-row"><span class="office-dot info">i</span><div><b>${RULES.length} wersjonowanych reguł</b><small>Stan merytoryczny reguł: 28.09.2026</small></div></div>`}

function renderLegal(){const q=($('#legalSearch')?.value||'').toLowerCase(),filter=$('#legalStatusFilter')?.value||'',box=$('#legalRules'),sum=$('#legalSummary');if(!box||!sum)return;const statuses=legalStatuses(),sm=new Map((statuses.sources||[]).map(x=>[x.id,x]));const list=RULES.filter(r=>(!filter||r.status===filter)&&(!q||[r.title,r.area,r.summary,r.sourceName].join(' ').toLowerCase().includes(q)));sum.innerHTML=`<div class="office-kpi"><span>Reguły</span><b>${RULES.length}</b><small>${RULES.filter(x=>x.status==='current').length} obowiązujących</small></div><div class="office-kpi"><span>Zweryfikowano</span><b>${RULES.filter(x=>x.verified).length}</b><small>merytorycznie</small></div><div class="office-kpi"><span>Źródła online</span><b>${[...sm.values()].filter(x=>x.ok).length}</b><small>z ostatniego sprawdzenia</small></div><div class="office-kpi"><span>Ostatnia kontrola</span><b class="small-value">${statuses.checkedAt?new Date(statuses.checkedAt).toLocaleDateString('pl-PL'):'—'}</b><small>${statuses.checkedAt?new Date(statuses.checkedAt).toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'}):'uruchom sprawdzenie'}</small></div>`;box.innerHTML=list.map(r=>{const st=sm.get(r.id);return`<article class="legal-rule"><div class="legal-rule-top"><div><span class="form-pill ${r.status==='current'?'green':'amber'}">${r.status==='current'?'OBOWIĄZUJE':'PLANOWANE'}</span><span class="legal-area">${esc(r.area)}</span></div><span class="legal-online ${st?st.ok?'ok':'bad':'unknown'}">${st?st.ok?'źródło online':'źródło niedostępne':'nie sprawdzano'}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p><div class="legal-meta"><span>Od: <b>${esc(r.from)}</b></span><span>Zweryfikowano: <b>${esc(r.verified)}</b></span></div><a href="${esc(r.source)}" target="_blank" rel="noopener">${esc(r.sourceName)} ↗</a></article>`}).join('')||'<div class="office-empty">Brak reguł pasujących do filtra.</div>'}
async function refreshLegal(){const b=$('#legalRefreshBtn');if(b){b.disabled=true;b.textContent='Sprawdzam…'}try{const r=await fetch('/api/legal/status',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);saveJson(LEGAL_STATUS_KEY,j);renderLegal();renderDashboard()}catch(e){alert('Nie udało się sprawdzić źródeł: '+(e.message||e))}finally{if(b){b.disabled=false;b.textContent='Sprawdź dostępność źródeł'}}}

async function comparePdfXml(){const p=$('#comparePdfInput')?.files?.[0],x=$('#compareXmlInput')?.files?.[0],out=$('#comparePdfXmlResult');if(!p||!x){out.innerHTML='<div class="office-alert warn">Wybierz PDF i XML tej samej faktury.</div>';return}out.innerHTML='<div class="office-empty compact">Analizuję dokumenty…</div>';try{const data=await new Promise((res,rej)=>{const r=new FileReader();r.onerror=()=>rej(r.error);r.onload=()=>res(String(r.result));r.readAsDataURL(p)}),base64=data.split(',')[1];const pr=await fetch('/api/pdf/extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:p.name,data:base64})}),pj=await pr.json();if(!pr.ok||!pj.hasText)throw new Error(pj.error||'PDF nie ma warstwy tekstowej');const parses=[pj.layoutText,pj.text].filter(Boolean).map(window.pdfImport.parseText),pd=window.pdfImport.mergeParses(parses);const xml=await x.text(),doc=new DOMParser().parseFromString(xml,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw new Error('XML nie jest poprawnym dokumentem');const xi=window.invoice?window.invoice(doc):invoice(doc);const xNet=(xi.rows||[]).reduce((s,r)=>s+num(r.net),0),xVat=(xi.rows||[]).reduce((s,r)=>s+num(r.vat),0);const rows=[['Numer faktury',pd.number,xi.number],['Data wystawienia',pd.date,xi.date],['NIP sprzedawcy',pd.seller?.nip,xi.seller?.nip],['NIP nabywcy',pd.buyer?.nip,xi.buyer?.nip],['Netto',pd.net,xNet],['VAT',pd.vat,xVat],['Brutto',pd.gross,num(xi.total)],['Rachunek',pd.banks?.[0],xi.banks?.[0]?.nr||xi.bankNo]];out.innerHTML=`<div class="compare-result-table">${rows.map(([label,a,b])=>{const numeric=['Netto','VAT','Brutto'].includes(label),ok=numeric?Math.abs(num(a)-num(b))<.02:String(a||'').replace(/\s/g,'')===String(b||'').replace(/\s/g,'');return`<div class="compare-line ${ok?'ok':'bad'}"><span>${ok?'✓':'×'}</span><b>${esc(label)}</b><div><small>PDF</small>${numeric?money(a):esc(a||'—')}</div><div><small>XML</small>${numeric?money(b):esc(b||'—')}</div></div>`}).join('')}</div>`}catch(e){out.innerHTML=`<div class="office-alert error">${esc(e.message||e)}</div>`}}

function reportClient(){const c=current(),f=forecast(c),hs=clientHistory(c).slice(0,20),h=linkedHealth(c),assets=c.assets||[];const w=window.open('','_blank');if(!w){alert('Zezwól na wyskakujące okna.');return}const css='body{font:12px Arial;color:#172033;margin:28px}h1{margin:0}h2{margin-top:24px;border-bottom:1px solid #ddd;padding-bottom:5px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.k{border:1px solid #ddd;border-radius:8px;padding:10px}.k span{display:block;color:#667085}.k b{font-size:16px}table{width:100%;border-collapse:collapse}th,td{padding:7px;border-bottom:1px solid #eee;text-align:left}.note{background:#f6f8fb;padding:10px;border-radius:8px}.muted{color:#667085}';w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Pakiet klienta — ${esc(c.name)}</title><style>${css}</style></head><body><h1>${esc(c.name)}</h1><div class="muted">NIP ${esc(c.nip||'—')}${c.regon?` · REGON ${esc(c.regon)}`:''}${c.krs?` · KRS ${esc(c.krs)}`:''} · ${esc(fmtForm(c.taxForm))} · raport ${new Date().toLocaleDateString('pl-PL')}</div><h2>Profil</h2><div class="grid"><div class="k"><span>VAT</span><b>${esc(c.vatStatus)}</b></div><div class="k"><span>Rachunek</span><b>${esc(c.bank||'—')}</b></div><div class="k"><span>Kontrole faktur</span><b>${hs.length}</b></div><div class="k"><span>Środki trwałe</span><b>${assets.length}</b></div></div><h2>Prognoza podatkowa</h2>${f.available?`<div class="grid"><div class="k"><span>Przychód YTD</span><b>${money(f.revenue)}</b></div><div class="k"><span>Prognoza PIT</span><b>${money(f.pit)}</b></div><div class="k"><span>Prognoza zdrowotnej</span><b>${money(f.health)}</b></div><div class="k"><span>Rezerwa / miesiąc</span><b>${money(f.reserve)}</b></div></div><p class="note">Prognoza bazuje na annualizacji ${f.n} miesięcy i ma charakter planistyczny.</p>`:'<p>Brak danych miesięcznych do prognozy.</p>'}<h2>Składka zdrowotna</h2><p>${h?`Profil powiązany: ${esc(h.name)} (${esc(fmtForm(h.form))}).`:'Brak powiązanego profilu.'}</p><h2>Ostatnie kontrole faktur</h2><table><tr><th>Faktura</th><th>Data kontroli</th><th>Wynik</th></tr>${hs.map(x=>`<tr><td>${esc(x.invoiceNumber||x.fileName)}</td><td>${new Date(x.at).toLocaleDateString('pl-PL')}</td><td>${x.errors||0} bł. / ${x.warns||0} ostrz.</td></tr>`).join('')}</table><h2>Środki trwałe</h2><table><tr><th>Nazwa</th><th>Wartość</th><th>Umorzenie</th><th>Niezamortyzowana</th></tr>${assets.map(a=>{const r=assetResult(a);return`<tr><td>${esc(a.name)}</td><td>${money(a.initial)}</td><td>${money(a.depreciated)}</td><td>${money(r.remaining)}</td></tr>`}).join('')}</table><h2>Notatki</h2><p>${esc(c.notes||'—')}</p><script>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()}

function exportBackup(){const data={version:'2.5.1',createdAt:nowIso(),storage:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&(/ksef/i.test(k)||/health/i.test(k)))data.storage[k]=localStorage.getItem(k)}const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ksef-checker-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importBackup(file){try{const j=JSON.parse(await file.text());if(!j.storage||typeof j.storage!=='object')throw new Error('Nieprawidłowy format kopii');if(!confirm('Przywrócić dane z kopii? Bieżące lokalne dane objęte kopią zostaną zastąpione.'))return;for(const [k,v] of Object.entries(j.storage))localStorage.setItem(k,v);alert('Dane przywrócone. Strona zostanie przeładowana.');location.reload()}catch(e){alert('Nie udało się przywrócić kopii: '+(e.message||e))}}
function csvRows(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim()),sep=(lines[0]?.match(/;/g)||[]).length>(lines[0]?.match(/,/g)||[]).length?';':',';const parse=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===sep&&!q){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out};const arr=lines.map(parse),head=arr.shift().map(x=>x.toLowerCase());return arr.map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]||''])))}
function rowToClient(r){const get=(...ks)=>{for(const k of ks)if(r[k]!=null&&String(r[k]).trim()!=='')return String(r[k]).trim();return''},formRaw=get('forma','forma opodatkowania','taxform').toLowerCase();const vatRaw=get('vat','status vat').toLowerCase();return normalizeClient({id:uid('client'),name:get('nazwa','klient','firma','name')||'Importowany klient',nip:get('nip').replace(/\D/g,''),taxForm:/lini/.test(formRaw)?'linear':/rycz/.test(formRaw)?'ryc':'scale',rycRate:get('stawka ryczałtu','ryczałt','rycrate')||'8.5',vatStatus:/czyn|active/.test(vatRaw)?'active':/zwol|exempt/.test(vatRaw)?'exempt':/nieakt|inactive/.test(vatRaw)?'inactive':'unknown',email:get('email','e-mail'),bank:get('rachunek','konto','bank'),regon:get('regon'),krs:get('krs'),address:get('adres','address'),createdAt:nowIso(),updatedAt:nowIso()})}
async function importClients(file){try{let rows=[];if(/\.csv$/i.test(file.name))rows=csvRows(await file.text());else{if(!window.ExcelJS)throw new Error('Brak modułu ExcelJS');const wb=new ExcelJS.Workbook();await wb.xlsx.load(await file.arrayBuffer());const ws=wb.worksheets[0],heads=[];ws.getRow(1).eachCell((c,i)=>heads[i-1]=String(c.text||'').trim().toLowerCase());ws.eachRow((row,n)=>{if(n===1)return;const o={};heads.forEach((h,i)=>o[h]=String(row.getCell(i+1).text||'').trim());if(Object.values(o).some(Boolean))rows.push(o)})}const imported=rows.map(rowToClient);if(!imported.length)throw new Error('Nie znaleziono danych klientów');clients.push(...imported);activeId=imported[0].id;save();renderClient();renderDashboard();alert(`Zaimportowano ${imported.length} klientów.`)}catch(e){alert('Import nie powiódł się: '+(e.message||e))}}
function addClient(){const c=blankClient(`Klient ${clients.length+1}`);clients.push(c);activeId=c.id;save();renderClient();renderDashboard();showView('clients')}
function duplicateClient(){const c=JSON.parse(JSON.stringify(current()));c.id=uid('client');c.name=(c.name||'Klient')+' — kopia';c.createdAt=nowIso();c.updatedAt=nowIso();clients.push(c);activeId=c.id;save();renderClient();renderDashboard()}
function deleteClient(){if(clients.length===1){alert('Musi pozostać co najmniej jeden klient.');return}const c=current();if(!confirm(`Usunąć kartotekę „${c.name}”?`))return;clients=clients.filter(x=>x.id!==c.id);activeId=clients[0].id;save();renderClient();renderDashboard()}
function openHealth(){const c=current(),h=linkedHealth(c);if(h&&window.healthCalc?.selectClient)window.healthCalc.selectClient(h.id);showView('healthCalc')}
function openTax(){const c=current(),h=linkedHealth(c),rows=monthsWithData(h),rev=rows.reduce((s,m)=>s+num(m.revenue),0),cost=rows.reduce((s,m)=>s+num(m.costs),0),soc=rows.reduce((s,m)=>s+num(m.social),0);showView('taxSimulator');setTimeout(()=>window.taxSimulator?.prefill?.({client:c.name,revenue:rev,costs:cost,social:soc,form:c.taxForm,rycRate:c.rycRate}),50)}
function bind(){
 $('#clientRegistryFetch')?.addEventListener('click',()=>fetchClientRegistry(true));$('#clientNip')?.addEventListener('input',e=>{const el=e.currentTarget;el.value=String(el.value||'').replace(/\D/g,'').slice(0,10);clearTimeout(registryFetchTimer);if(el.value.length===10)registryFetchTimer=setTimeout(()=>fetchClientRegistry(false),650)});
 $('#clientAddBtn')?.addEventListener('click',addClient);$('#dashNewClient')?.addEventListener('click',addClient);$('#clientDuplicateBtn')?.addEventListener('click',duplicateClient);$('#clientDeleteBtn')?.addEventListener('click',deleteClient);$('#clientReportBtn')?.addEventListener('click',reportClient);$('#assetAddBtn')?.addEventListener('click',addAsset);$('#clientOpenHealth')?.addEventListener('click',openHealth);$('#clientOpenTaxSim')?.addEventListener('click',openTax);$('#clientOpenHistory')?.addEventListener('click',()=>showView('history'));$('#comparePdfXmlBtn')?.addEventListener('click',comparePdfXml);
 ['clientName','clientNip','clientTaxForm','clientRycRate','clientVatStatus','clientEmail','clientBank','clientHealthLink','clientTaxPaid','clientHealthPaid','clientNotes'].forEach(id=>$('#'+id)?.addEventListener('change',bindClientForm));
 $('#backupExportBtn')?.addEventListener('click',exportBackup);$('#backupImportBtn')?.addEventListener('click',()=>$('#backupImportInput').click());$('#backupImportInput')?.addEventListener('change',e=>{if(e.target.files[0])importBackup(e.target.files[0])});$('#clientImportBtn')?.addEventListener('click',()=>$('#clientImportInput').click());$('#clientImportInput')?.addEventListener('change',e=>{if(e.target.files[0])importClients(e.target.files[0])});
 $('#dashRefresh')?.addEventListener('click',()=>{syncFromHealth();save(false);renderDashboard();renderClient()});$$('[data-office-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.officeGo)));$('#legalRefreshBtn')?.addEventListener('click',refreshLegal);$('#legalSearch')?.addEventListener('input',renderLegal);$('#legalStatusFilter')?.addEventListener('change',renderLegal);
}
function init(){if(!$('#clientsView'))return;load();renderClient();renderDashboard();renderLegal();bind();window.addEventListener('ksef:health-clients-changed',()=>{syncFromHealth();save(false);renderClient();renderDashboard()});window.numberFormatter?.apply?.($('#clientsView'))}
window.officeHub={renderDashboard,renderClient,renderLegal,get clients(){return clients},current,forecast,exportBackup,fetchClientRegistry,RULES};
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
