(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let lastResults=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function add(group,name,status,detail=''){lastResults.push({group,name,status,detail,time:new Date().toISOString()});updateSummary()}
function updateSummary(){const total=lastResults.length,passed=lastResults.filter(x=>x.status==='pass').length,failed=lastResults.filter(x=>x.status==='fail').length,warned=lastResults.filter(x=>x.status==='warn').length;$('#qaTotal').textContent=total;$('#qaPassed').textContent=passed;$('#qaFailed').textContent=failed;$('#qaWarned').textContent=warned}
function progress(done,total,text=''){const box=$('#qaProgress');box.classList.remove('hidden');const pct=total?Math.round(done/total*100):0;$('#qaProgressBar').style.width=pct+'%';$('#qaProgressText').textContent=text||`${done}/${total}`}
async function test(group,name,fn,{warnOnError=false}={}){try{const r=await fn();if(r===false)throw new Error('Warunek testu nie został spełniony.');const detail=typeof r==='string'?r:r?.detail||'';add(group,name,r?.status||'pass',detail)}catch(e){add(group,name,warnOnError?'warn':'fail',e?.message||String(e))}}
function parserOk(xml){const d=new DOMParser().parseFromString(xml,'application/xml');return !d.getElementsByTagName('parsererror').length}
function render(){const box=$('#qaGroups');if(!box)return;const groups=[...new Set(lastResults.map(x=>x.group))];box.innerHTML=groups.map(g=>{const a=lastResults.filter(x=>x.group===g),p=a.filter(x=>x.status==='pass').length,f=a.filter(x=>x.status==='fail').length,w=a.filter(x=>x.status==='warn').length;return `<details class="qa-group" ${f?'open':''}><summary><span>${esc(g)}</span><span class="qa-group-counts"><b class="ok">${p} ✓</b>${w?`<b class="warn">${w} !</b>`:''}${f?`<b class="error">${f} ×</b>`:''}</span></summary><div class="qa-test-list">${a.map(x=>`<div class="qa-test ${x.status}"><span>${x.status==='pass'?'✓':x.status==='fail'?'×':'!'}</span><div><b>${esc(x.name)}</b>${x.detail?`<small>${esc(x.detail)}</small>`:''}</div></div>`).join('')}</div></details>`}).join('')||'<div class="qa-empty">Brak wyników.</div>'}
function saveInputs(ids){const vals={};ids.forEach(id=>{const e=$('#'+id);if(e)vals[id]={value:e.value,checked:e.checked}});return()=>Object.entries(vals).forEach(([id,v])=>{const e=$('#'+id);if(e){e.value=v.value;e.checked=v.checked}})}
function setVal(id,v){const e=$('#'+id);if(e)e.value=String(v)}
async function runUiToolTests(){
 const group='Toolbox — logika i granice';
 await test(group,'MPP: dokładnie 15 000,00 zł nie przekracza progu',async()=>{const restore=saveInputs(['tbMppGross','tbMppCurrency','tbMppRate','tbMppSensitive','tbMppSellerVat','tbMppBuyerVat']);try{setVal('tbMppGross','15000');setVal('tbMppCurrency','PLN');setVal('tbMppSensitive','yes');setVal('tbMppSellerVat','yes');setVal('tbMppBuyerVat','yes');$('#tbMppRun').click();return /nie jest obowiązkowy z uwagi na próg/i.test($('#tbMppResult').textContent)}finally{restore()}});
 await test(group,'MPP: 15 000,01 zł + załącznik 15 + VAT => obowiązkowy',async()=>{const restore=saveInputs(['tbMppGross','tbMppCurrency','tbMppRate','tbMppSensitive','tbMppSellerVat','tbMppBuyerVat']);try{setVal('tbMppGross','15000.01');setVal('tbMppCurrency','PLN');setVal('tbMppSensitive','yes');setVal('tbMppSellerVat','yes');setVal('tbMppBuyerVat','yes');$('#tbMppRun').click();return /Obowiązkowy MPP/i.test($('#tbMppResult').textContent)}finally{restore()}});
 await test(group,'Termin zwykłej faktury: 24.09.2026 → 15.10.2026',()=>typeof standardInvoiceDeadline==='function'&&standardInvoiceDeadline('2026-09-24')==='2026-10-15');
 await test(group,'Walidator NIP odrzuca nieprawidłowy numer',()=>typeof nipOk==='function'&&!nipOk('1234567890'));
 await test(group,'Kalkulator VAT: 100 netto przy 23% daje 123 brutto',async()=>{const row=$('#tbVatRows .vat-calc-row');if(!row)throw new Error('Brak wiersza VAT');const amount=row.querySelector('.v-amount'),mode=row.querySelector('.v-mode'),rate=row.querySelector('.v-rate');const old=[amount.value,mode.value,rate.value];try{amount.value='100';mode.value='net';rate.value='23';amount.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(r=>setTimeout(r,10));return /123,00/.test(row.querySelector('.v-result').textContent)}finally{[amount.value,mode.value,rate.value]=old;amount.dispatchEvent(new Event('input',{bubbles:true}))}});
 await test(group,'Leasing: kalkulator zwraca proporcję KUP',async()=>{const restore=saveInputs(['tbLeaseCarType','tbLeaseCarNet','tbLeaseVatRate','tbLeaseVatDeduction','tbLeaseCapitalNet','tbLeaseInterestNet']);try{setVal('tbLeaseCarType','high');setVal('tbLeaseCarNet','180000');setVal('tbLeaseVatRate','23');setVal('tbLeaseVatDeduction','50');setVal('tbLeaseCapitalNet','3000');setVal('tbLeaseInterestNet','500');$('#tbLeaseRun').click();return /Proporcja KUP/i.test($('#tbLeaseResult').textContent)}finally{restore()}});
 await test(group,'Polisa AC: wartość >150 tys. uruchamia proporcję',async()=>{const restore=saveInputs(['tbInsType','tbInsPremium','tbInsCarValue']);try{setVal('tbInsType','value');setVal('tbInsPremium','6000');setVal('tbInsCarValue','220000');$('#tbInsRun').click();return /Proporcja KUP/i.test($('#tbInsResult').textContent)}finally{restore()}});
 await test(group,'Różnica kursowa: identyczne kursy => brak różnicy',async()=>{const restore=saveInputs(['tbFxType','tbFxAmount','tbFxInvoiceRate','tbFxPaymentRate']);try{setVal('tbFxType','receivable');setVal('tbFxAmount','1000');setVal('tbFxInvoiceRate','4.3');setVal('tbFxPaymentRate','4.3');$('#tbFxRun').click();return /Brak różnicy kursowej/i.test($('#tbFxResult').textContent)}finally{restore()}});
}
async function runPdfTests(){
 const group='PDF — parser i tryb kontroli';
 const sample=`FAKTURA VAT nr FV/09/2026/123\nData wystawienia: 24.09.2026\nData sprzedaży: 23.09.2026\nSprzedawca\nBiuro Alfa Sp. z o.o.\nNIP: 7018107174\nul. Księgowa 12\n00-001 Warszawa\nNabywca\nKlient Testowy Sp. z o.o.\nNIP: 5250001003\nul. Przykładowa 8\n01-100 Warszawa\nNetto VAT Brutto\n23% 1000,00 230,00 1230,00\nRazem netto 1000,00 PLN\nKwota VAT 230,00 PLN\nDo zapłaty 1230,00 PLN\nTermin płatności: 07.10.2026\nRachunek: 61 1090 1014 0000 0712 1981 2874`;
 await test(group,'Parser PDF rozpoznaje numer faktury',()=>window.pdfImport?.parseText(sample)?.number==='FV/09/2026/123');
 await test(group,'Parser PDF rozpoznaje datę wystawienia',()=>window.pdfImport?.parseText(sample)?.date==='2026-09-24');
 await test(group,'Parser PDF rozpoznaje NIP obu stron',()=>{const d=window.pdfImport?.parseText(sample);return d?.seller?.nip==='7018107174'&&d?.buyer?.nip==='5250001003'});
 await test(group,'Parser PDF rozpoznaje podsumowanie VAT 23%',()=>{const d=window.pdfImport?.parseText(sample);return d?.vatGroups?.some(x=>x.rate==='23'&&Math.abs(x.net-1000)<.01&&Math.abs(x.vat-230)<.01)});
 await test(group,'Parser PDF rozpoznaje rachunek bankowy',()=>window.pdfImport?.parseText(sample)?.banks?.[0]==='61109010140000071219812874');
 await test(group,'Parser PDF rozróżnia datę wystawienia, sprzedaży i płatności w jednym wierszu',()=>{const d=window.pdfImport?.parseText(`Faktura FV/9/2026\nData sprzedaży: 22.09.2026    Data wystawienia: 24.09.2026    Termin płatności: 01.10.2026\nRazem netto 2000,00  Kwota VAT 460,00  Razem brutto 2460,00`);return d?.date==='2026-09-24'&&d?.saleDate==='2026-09-22'&&d?.paymentDate==='2026-10-01'});
 await test(group,'Parser PDF uzgadnia netto + VAT = brutto w jednej linii',()=>{const d=window.pdfImport?.parseText(`Faktura FV/1/2026\nData wystawienia 24.09.2026\nRazem netto 2 000,00    Kwota VAT 460,00    Razem brutto 2 460,00`);return Math.abs(d.net-2000)<.01&&Math.abs(d.vat-460)<.01&&Math.abs(d.gross-2460)<.01});
 await test(group,'Parser PDF odczytuje tabelę z nagłówkiem Netto / VAT / Brutto',()=>{const d=window.pdfImport?.parseText(`Faktura FV/2/2026\nWystawiono 24 września 2026\nNetto          VAT          Brutto\n1 500,00       345,00       1 845,00`);return d?.date==='2026-09-24'&&Math.abs(d.net-1500)<.01&&Math.abs(d.vat-345)<.01&&Math.abs(d.gross-1845)<.01});
 await test(group,'Parser PDF obsługuje format kwot 1,234.56',()=>{const d=window.pdfImport?.parseText(`INVOICE INV-1\nIssue date: 2026-09-24\nNet amount: 1,234.56 USD\nVAT amount: 283.95 USD\nTotal due: 1,518.51 USD`);return Math.abs(d.net-1234.56)<.01&&Math.abs(d.vat-283.95)<.01&&Math.abs(d.gross-1518.51)<.01});
 await test(group,'Parser PDF nie myli ceny jednostkowej z kwotą końcową',()=>{const d=window.pdfImport?.parseText(`Faktura FV/3/2026\nData wystawienia 24.09.2026\nCena jednostkowa 12,30\nRazem netto 10 000,00\nPodatek VAT 2 300,00\nKwota do zapłaty 12 300,00`);return Math.abs(d.net-10000)<.01&&Math.abs(d.vat-2300)<.01&&Math.abs(d.gross-12300)<.01});

 await test(group,'Numer faktury nie może być rachunkiem PL + 26 cyfr',()=>window.pdfImport?.parseText(`Numer faktury\nPL87105013991000009087252913\nNIP 6462686354\nNIP 9540000000`)?.number==='');
 await test(group,'Numer faktury nie może być 26-cyfrowym rachunkiem NRB',()=>window.pdfImport?.parseText(`Numer faktury\n73114020040000300284412749\nNIP 6462686354\nNIP 9540000000`)?.number==='');
 await test(group,'Luźny numer WZ nie jest traktowany jak numer faktury',()=>window.pdfImport?.parseText(`Numer faktury\nWZ8879/09/2026\nNIP 6462686354\nNIP 9540000000`)?.number==='');
 await test(group,'Jawny numer faktury po etykiecie jest zachowany',()=>window.pdfImport?.parseText(`Numer faktury: FV/8879/09/2026\nNIP 6462686354\nNIP 9540000000`)?.number==='FV/8879/09/2026');
 await test(group,'Parser PDF ignoruje link QR pl/invoice jako numer faktury',()=>{const d=window.pdfImport?.parseText(`pl/invoice/6462686354/31-08-2026/pidtcSxDntJSmzqfF8Ay3Z\nNazwa: TEST SP. Z O.O. Adres: PUŁAWSKA 12, 02-566 WARSZAWA NIP: 6462686354\nNIP: 9540000000\nRazem netto 100,00\nVAT 23,00\nBrutto 123,00`);return d?.number===''&&d?.date==='2026-08-31'&&d?.seller?.nip==='6462686354'});
 await test(group,'Parser PDF używa daty P_1 z linku weryfikacyjnego KSeF',()=>window.pdfImport?.parseText(`https://example.pl/pl/invoice/6462686354/01-09-2026/ABCDEFG123456789\nNIP 6462686354\nNIP 9540000000`)?.date==='2026-09-01');
 await test(group,'Parser PDF nie dokleja Adres/NIP do nazwy firmy',()=>{const d=window.pdfImport?.parseText(`pl/invoice/6462686354/31-08-2026/ABCDEFG123456789\nNazwa: DANIEL CYMA CONSULTING Adres: PUŁAWSKA 12, 02-566 WARSZAWA NIP: 6462686354\nNazwa: ACME SP. Z O.O. Adres: ROLNA 43/11, 43-100 TYCHY NIP: 9540000000`);return d?.seller?.name==='DANIEL CYMA CONSULTING'&&d?.buyer?.name==='ACME SP. Z O.O.'});
 await test(group,'Model PDF tworzy poprawny syntetyczny XML roboczy',()=>{const d=window.pdfImport?.parseText(sample),xml=window.pdfImport?.syntheticXml(d);return !!xml&&parserOk(xml)&&/PDF_IMPORT/.test(xml)});
 await test(group,'Interfejs ma edycję danych rozpoznanych z PDF',()=>!!$('#pdfReviewCard')&&!!$('#pdfApplyEdits')&&!!$('#pdfRawText'));
 await test(group,'Lokalny endpoint wydobywa tekst z przykładowego PDF',async()=>{const r=await fetch('samples/17_pdf_test_invoice.pdf',{cache:'no-store'});if(!r.ok)throw new Error(`Brak próbki PDF: HTTP ${r.status}`);const ab=await r.arrayBuffer(),u=new Uint8Array(ab);let bin='';for(let i=0;i<u.length;i+=0x8000)bin+=String.fromCharCode(...u.subarray(i,i+0x8000));const b64=btoa(bin),x=await fetch('/api/pdf/extract',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'17_pdf_test_invoice.pdf',data:b64})}),j=await x.json();if(!x.ok)throw new Error(j.error||`HTTP ${x.status}`);if(!j.hasText||!/FV\/09\/2026\/123/.test(j.text||''))throw new Error('Parser PDF nie odczytał oczekiwanego tekstu.');return`${j.engine||'parser'} · ${j.text.length} znaków`});
}
async function runRuleExpectations(){
 const group='Checker — reguły biznesowe';
 const cases=[
  ['samples/03_reverse_charge_brak_p18.xml',/P_18|reverse charge/i,'Brak P_18 dla reverse charge jest wykrywany'],
  ['samples/05_korekta_bez_przyczyny.xml',/PrzyczynaKorekty|przyczyn/i,'Korekta bez przyczyny jest wykrywana'],
  ['samples/08_mpp_brak_adnotacji.xml',/MPP|P_18A/i,'Brak adnotacji MPP jest wykrywany'],
  ['samples/10_eur_brak_vat_w_pln.xml',/P_14|PLN|walut/i,'Brak VAT w PLN na fakturze walutowej jest sygnalizowany'],
  ['test-library/negative/NEG_01_invalid_nip.xml',/NIP/i,'Nieprawidłowy NIP jest wykrywany'],
  ['test-library/negative/NEG_02_wrong_vat_math.xml',/VAT|P_14|kwot/i,'Błędna matematyka VAT jest wykrywana'],
  ['test-library/negative/NEG_03_wrong_total.xml',/P_15|suma|razem/i,'Błędna suma faktury jest wykrywana'],
  ['test-library/negative/NEG_05_missing_invoice_number.xml',/P_2|numer faktury/i,'Brak numeru faktury jest wykrywany']
 ];
 for(const [url,re,name] of cases)await test(group,name,async()=>{if(typeof ruleChecks!=='function')throw new Error('Funkcja ruleChecks nie jest dostępna.');const xml=await fetch(url,{cache:'no-store'}).then(r=>r.text()),doc=new DOMParser().parseFromString(xml,'application/xml'),checks=ruleChecks(doc);return re.test(checks.map(x=>`${x.title} ${x.desc} ${x.field}`).join(' '))?`Wykryto ${checks.filter(x=>x.type==='error'||x.type==='warn').length} problemów.`:false});
}
async function runQa(){
 const btn=$('#qaRunBtn');btn.disabled=true;btn.textContent='Testuję…';lastResults=[];updateSummary();$('#qaGroups').innerHTML='<div class="qa-empty">Trwa wykonywanie testów…</div>';$('#qaExportBtn').disabled=true;
 const live=!!$('#qaLiveServices').checked;let done=0,totalHint=150;progress(done,totalHint,'Sprawdzam serwer lokalny…');
 await test('Środowisko','Lokalny serwer odpowiada',async()=>{const r=await fetch('/api/health',{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw new Error('Brak odpowiedzi /api/health');return`wersja ${j.version}`});done++;progress(done,totalHint);
 let server=null;await test('Środowisko','Pliki wymagane przez aplikację istnieją',async()=>{const r=await fetch('/api/qa/server',{cache:'no-store'});server=await r.json();const bad=(server.files||[]).filter(x=>!x.ok);if(bad.length)throw new Error('Brak: '+bad.map(x=>x.name).join(', '));return`${server.files.length} plików bazowych OK · Node ${server.node}`});done++;if(server)add('Środowisko','Lokalny parser PDF (pdf-parse)',server.pdfParserInstalled?'pass':'warn',server.pdfParserInstalled?'Zależność gotowa.':'Zostanie zainstalowana przez START_CHECKER.bat przy pierwszym uruchomieniu.');if(server)add('Środowisko','Renderer podglądu PDF.js',server.pdfRendererInstalled?'pass':'warn',server.pdfRendererInstalled?'Silnik renderowania oryginalnego PDF jest dostępny lokalnie.':'Brak silnika PDF.js w pdf-parse — uruchom START_CHECKER.bat ponownie.');if(server)add('Środowisko','Eksport Excel (ExcelJS)',server.excelInstalled?'pass':'warn',server.excelInstalled?'Moduł .xlsx jest dostępny lokalnie.':'ExcelJS zostanie zainstalowany przez START_CHECKER.bat.');
 const manifest=await fetch('test-library/manifest.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('Nie można wczytać manifestu biblioteki');return r.json()}).catch(e=>{add('Biblioteka testowa','Manifest biblioteki','fail',e.message);return null});
 if(manifest){add('Biblioteka testowa','Liczba lokalnych XML zgodna z manifestem',manifest.xmlCount===46?'pass':'warn',`manifest: ${manifest.xmlCount}`);const xmls=(manifest.entries||[]).filter(x=>x.kind==='xml');totalHint=Math.max(totalHint,20+xmls.length*2+40);for(const e of xmls){let xml='';await test('Biblioteka — dostępność',`${e.file} — plik dostępny`,async()=>{const r=await fetch(e.file,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);xml=await r.text();return`${xml.length} znaków`});done++;await test('Biblioteka — XML',`${e.file} — well-formed XML`,()=>xml&&parserOk(xml));done++;if(done%8===0)progress(done,totalHint,`Biblioteka XML: ${done} testów wykonanych…`)}}
 // UI/source coverage
 const cards=$$('.tool-card');for(const c of cards){const name=c.querySelector('b')?.textContent||c.dataset.tool;await test('Toolbox — kompletność',`${name}: kafelek ma panel`,()=>!!document.querySelector(`[data-tool-panel="${CSS.escape(c.dataset.tool)}"]`));const panel=document.querySelector(`[data-tool-panel="${CSS.escape(c.dataset.tool)}"]`);await test('Toolbox — źródła',`${name}: ma źródło i datę weryfikacji`,()=>{const src=panel?.querySelector('.official-check'),link=src?.querySelector('a[href^="http"]'),law=src?.querySelector('.law-state');if(!src||!link||!law)throw new Error('Brak linku źródłowego lub daty stanu prawnego.');return law.textContent});done+=2}
 await runRuleExpectations();done+=8;progress(done,totalHint,'Testuję kalkulatory i przypadki graniczne…');await runUiToolTests();done+=8;await runPdfTests();done+=8;
 await test('Kalkulator podatkowy','Skala 2026: 120 000 zł => 10 800 zł PIT',()=>window.taxSimulator?.scaleTax(120000)===10800);
 await test('Kalkulator podatkowy','Skala 2026: 150 000 zł => 20 400 zł PIT',()=>window.taxSimulator?.scaleTax(150000)===20400);
 await test('Kalkulator podatkowy','Zdrowotna ryczałt: 100 000 zł / 12 mies. => 9 966,96 zł',()=>Math.abs(window.taxSimulator?.autoHealth('ryc',0,100000,12)-9966.96)<0.01);
 await test('Kalkulator podatkowy','Interfejs ma 3 formy, wykresy i eksport PDF',()=>!!$('#taxSimulatorView')&&!!$('#taxBurdenChart')&&!!$('#taxSensitivityChart')&&!!$('#taxSimExport'));
 await test('Składka zdrowotna','Nowa zakładka ma klientów, tabelę roczną i eksporty',()=>!!$('#healthCalcView')&&!!$('#hcClientTabs')&&!!$('#hcTable')&&!!$('#hcExportExcel')&&!!$('#hcExportPdf'));
 await test('Składka zdrowotna','Ryczałt: 100 000 zł trafia do progu 60–300 tys.',()=>window.healthCalc?.tierFor(100000)?.basePct===1);
 await test('Składka zdrowotna','Ryczałt: 300 000,01 zł trafia do najwyższego progu',()=>window.healthCalc?.tierFor(300000.01)?.basePct===1.8);
 await test('Składka zdrowotna','Sprzedaż ŚT jest wyłączona z miesięcznego dochodu do zdrowotnej',()=>{const months=Array.from({length:12},()=>({active:true,revenue:'0',costs:'0',assetRevenue:'0',assetCost:'0',social:'0',incomeDirect:''}));months[0]={active:true,revenue:'200000',costs:'50000',assetRevenue:'100000',assetCost:'40000',social:'0',incomeDirect:''};const c={form:'scale',inputMode:'revenueCosts',decPrevIncome:'0',socialReduces:true,includeAssetsAnnual:false,janNextActive:true,months};const mc=window.healthCalc?.monthlyCalc(c);return Math.abs((mc?.incomes?.[0]||0)-90000)<0.01});
 await test('Składka zdrowotna','Skala/liniowy: sprzedaż ŚT może być dobrowolnie doliczona tylko rocznie',()=>{const months=Array.from({length:12},()=>({active:true,revenue:'0',costs:'0',assetRevenue:'0',assetCost:'0',social:'0',incomeDirect:''}));months[0]={active:true,revenue:'200000',costs:'50000',assetRevenue:'100000',assetCost:'40000',social:'0',incomeDirect:''};const base={form:'scale',inputMode:'revenueCosts',decPrevIncome:'0',socialReduces:true,janNextActive:true,months};const a1=window.healthCalc?.annualCalc({...base,includeAssetsAnnual:false},window.healthCalc.monthlyCalc({...base,includeAssetsAnnual:false}));const a2=window.healthCalc?.annualCalc({...base,includeAssetsAnnual:true},window.healthCalc.monthlyCalc({...base,includeAssetsAnnual:true}));return Math.abs(a1.income-90000)<0.01&&Math.abs(a2.income-150000)<0.01});
 await test('Składka zdrowotna','Pole „Do wykazania w DRA” jest tylko do odczytu',()=>!document.querySelector('#hcTable input[data-k="declared"],#hcTable input[data-k="janNextDeclared"]')&&!!document.querySelector('#hcTable .hc-dra-locked'));
 await test('Składka zdrowotna','Formy opodatkowania mają odrębne oznaczenie kolorystyczne',()=>!!$('#hcFormIndicator')&&['scale','linear','ryc'].every(x=>getComputedStyle($('#healthCalcView')).getPropertyValue('--hc-accent')!==''));
 await test('Separatory liczb','Formatter rozpoznaje 60 000 jako 60000',()=>window.numberFormatter?.parse('60 000')===60000);
 // XSD
 let xs=await fetch('/api/xsd/status',{cache:'no-store'}).then(r=>r.json()).catch(()=>({available:false}));if(!xs.available&&live){await test('XSD FA(3)','Synchronizacja oficjalnych schem XSD',async()=>{const r=await fetch('/api/xsd/sync',{method:'POST'}),j=await r.json();xs=j;if(!j.available)throw new Error((j.errors||[]).slice(-1)[0]||'Nie udało się pobrać schematu');return'4 lokalne pliki schematu zapisane';},{warnOnError:true})}else add('XSD FA(3)','Schemat FA(3) zapisany lokalnie',xs.available?'pass':'warn',xs.available?'Gotowy do walidacji offline po pobraniu.':'Schemat zostanie pobrany przy pierwszej walidacji z internetem.');
 if(xs.available&&manifest){const first=(manifest.entries||[]).find(x=>x.kind==='xml');await test('XSD FA(3)','Silnik XSD zwraca wynik dla XML',async()=>{const xml=await fetch(first.file).then(r=>r.text()),r=await fetch('/api/xsd/validate',{method:'POST',headers:{'Content-Type':'application/xml'},body:xml}),j=await r.json();if(!j.available)throw new Error('Silnik XSD niedostępny');return`silnik: ${j.engine}; próbka: ${j.ok?'zgodna':'niezgodna'} (${(j.errors||[]).length} komunikatów)`},{warnOnError:true})}
 // History/report elements
 await test('Interfejs','Historia kontroli ma lokalny magazyn i filtry',()=>!!$('#historyList')&&!!$('#historySearch')&&!!$('#historyStatusFilter'));await test('Interfejs','Przycisk raportu kontroli istnieje',()=>!!$('#reportBtn'));await test('Interfejs','Gazeta ma filtr daty i źródeł urzędowych',()=>!!$('#newsAgeFilter')&&!!$('#newsOfficialOnly')&&!!$('#newsMarkReadBtn'));await test('Interfejs','Analiza zbiorcza PDF ma wejście multiple',()=>!!$('#batchPdfInput')&&$('#batchPdfInput').multiple===true);await test('Interfejs','Analiza zbiorcza PDF ma tabelę i rozwijane wyniki',()=>!!$('#batchPanel')&&!!$('#batchRows')&&!!window.batchPdf?.handleFiles);await test('Interfejs','Moduł PDF umożliwia otwarcie przeanalizowanej faktury bez ponownej ekstrakcji',()=>typeof window.pdfImport?.loadAnalyzed==='function');
 await test('Biuro 2.5','Pulpit ma KPI, alerty i skróty',()=>!!$('#dashboardView')&&!!$('#dashboardKpis')&&!!$('#dashboardAlerts')&&!!$('#dashboardClients'));
 await test('Biuro 2.5','Kartoteka klienta ma profil, prognozę, historię i środki trwałe',()=>!!$('#clientsView')&&!!$('#clientName')&&!!$('#clientForecast')&&!!$('#clientHistory')&&!!$('#assetTable'));
 await test('Biuro 2.5','Kartoteka ma import, backup i raport klienta',()=>!!$('#clientImportBtn')&&!!$('#backupExportBtn')&&!!$('#backupImportBtn')&&!!$('#clientReportBtn'));
 await test('Biuro 2.5','Porównanie PDF ↔ XML jest dostępne',()=>!!$('#comparePdfInput')&&!!$('#compareXmlInput')&&!!$('#comparePdfXmlBtn'));
 await test('Biuro 2.5','Reguły prawne są wersjonowane i mają źródła',()=>Array.isArray(window.officeHub?.RULES)&&window.officeHub.RULES.length>=6&&window.officeHub.RULES.every(x=>x.from&&x.verified&&/^https:/.test(x.source)));
 await test('Biuro 2.5','Analiza zbiorcza ma filtry wyniku i problemu',()=>!!$('#batchSearch')&&!!$('#batchStatusFilter')&&!!$('#batchIssueFilter'));
 await test('Biuro 2.5.1','Kartoteka ma automatyczne pobieranie danych po NIP',()=>!!$('#clientRegistryFetch')&&!!$('#clientRegon')&&!!$('#clientKrs')&&!!$('#clientAddress')&&typeof window.officeHub?.fetchClientRegistry==='function');
 await test('Biuro 2.5.1','Kartoteka pokazuje status rejestru i listę rachunków',()=>!!$('#clientRegistryState')&&!!$('#clientRegistryAccounts'));
 if(live){progress(done,totalHint,'Testuję usługi internetowe…');await test('Integracje LIVE','NBP — kurs EUR zwraca dane',async()=>{const r=await fetch('/api/toolbox/nbp?currency=EUR&date=2026-09-24',{cache:'no-store'}),j=await r.json();if(!r.ok||!j.mid)throw new Error(j.error||'Brak kursu');return`${j.mid} PLN · ${j.date}`},{warnOnError:true});await test('Integracje LIVE','Gazeta — agregator zwraca źródła',async()=>{const r=await fetch('/api/news?refresh=1',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Brak newsów');if(!(j.sources||[]).length)throw new Error('Brak źródeł');return`${j.freshSources}/${j.sources.length} źródeł online · ${j.articles?.length||0} artykułów`},{warnOnError:true});await test('Integracje LIVE','Biała Lista MF — endpoint odpowiada',async()=>{const r=await fetch('/api/toolbox/contractor?nip=5260250274&date=2026-09-24',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return'API MF odpowiedziało'},{warnOnError:true})}
 render();progress(lastResults.length,lastResults.length,'Testy zakończone.');$('#qaProgress').classList.remove('hidden');$('#qaExportBtn').disabled=false;$('#qaLastRun').textContent='Ostatni test: '+new Date().toLocaleString('pl-PL');btn.disabled=false;btn.textContent='Uruchom pełny test';
}
function exportQa(){if(!lastResults.length)return;const blob=new Blob([JSON.stringify({version:'2.5.1',generatedAt:new Date().toISOString(),summary:{total:lastResults.length,passed:lastResults.filter(x=>x.status==='pass').length,failed:lastResults.filter(x=>x.status==='fail').length,warned:lastResults.filter(x=>x.status==='warn').length},results:lastResults},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ksef-checker-qa-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function init(){ $('#qaRunBtn')?.addEventListener('click',runQa);$('#qaExportBtn')?.addEventListener('click',exportQa);const q=new URLSearchParams(location.search);if(q.get('qa')==='1'){if(typeof showView==='function')showView('qa');if(q.get('live')==='1'&&$('#qaLiveServices'))$('#qaLiveServices').checked=true;setTimeout(runQa,350)} }
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
