(()=>{
'use strict';
window.KSEF_WORK_MODE=true;
const nativeFetch=window.fetch.bind(window);
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
const clean=v=>String(v??'').trim(), digits=v=>clean(v).replace(/\D/g,''), iso=v=>/^\d{4}-\d{2}-\d{2}$/.test(clean(v));
const round2=n=>Math.round((Number(n)+Number.EPSILON)*100)/100;
function dateShift(s,n){const d=new Date(`${s}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function b64ToBytes(s){const bin=atob(s),u=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)u[i]=bin.charCodeAt(i);return u}
function pdfLib(){const p=window.pdfjsLib||window.PDFJS;if(!p)throw new Error('Nie udało się załadować PDF.js. Sprawdź dostęp do cdnjs/jsDelivr w sieci firmowej.');try{if(p.GlobalWorkerOptions)p.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js'}catch{}return p}
async function pageLayout(page){const tc=await page.getTextContent({normalizeWhitespace:false,disableCombineTextItems:false});const items=(tc.items||[]).filter(x=>clean(x.str)).map(x=>({str:clean(x.str).replace(/\s+/g,' '),x:Number(x.transform?.[4]||0),y:Number(x.transform?.[5]||0),w:Number(x.width||0)}));const rows=[],tol=2.8;for(const it of items.sort((a,b)=>b.y-a.y||a.x-b.x)){let row=rows.find(r=>Math.abs(r.y-it.y)<=tol);if(!row){row={y:it.y,items:[]};rows.push(row)}row.items.push(it)}rows.sort((a,b)=>b.y-a.y);return rows.map(row=>{let line='',end=null;for(const it of row.items.sort((a,b)=>a.x-b.x)){if(end!==null){const gap=it.x-end;line+=gap>55?'     ':gap>18?'   ':gap>5?' ':''}line+=it.str;end=it.x+Math.max(it.w,it.str.length*4)}return line.trimEnd()}).filter(Boolean).join('\n')}
async function extractPdfPayload(payload){const raw=clean(payload?.data),name=clean(payload?.name)||'faktura.pdf';if(!raw)throw new Error('Brak danych PDF.');const bytes=b64ToBytes(raw);if(bytes.length>20*1024*1024)throw new Error('PDF jest większy niż 20 MB.');if(String.fromCharCode(...bytes.slice(0,5))!=='%PDF-')throw new Error('Plik nie wygląda jak poprawny PDF.');const p=pdfLib(),task=p.getDocument({data:bytes});const doc=await(task.promise||task);let textParts=[],layoutParts=[];for(let n=1;n<=doc.numPages;n++){const page=await doc.getPage(n),tc=await page.getTextContent();textParts.push((tc.items||[]).map(x=>x.str||'').join(' '));layoutParts.push(await pageLayout(page))}try{await doc.destroy()}catch{}const text=textParts.join('\n').replace(/\u0000/g,'').trim(),layoutText=layoutParts.join('\n\n').replace(/\u0000/g,'').trim();return{name,size:bytes.length,pages:doc.numPages||layoutParts.length,text,layoutText,info:{},hasText:(layoutText||text).replace(/\s/g,'').length>=30,engine:'PDF.js 3.11.174 · przeglądarka',previewId:'',previewUrl:''}}
async function getJson(url,opts={}){const r=await nativeFetch(url,{...opts,cache:'no-store'});let j=null;try{j=await r.json()}catch{}if(!r.ok)throw new Error(j?.message||j?.exception?.message||`HTTP ${r.status}`);return j}
async function whiteListSearch(nip,date){if(!/^\d{10}$/.test(nip)||!iso(date))return null;const j=await getJson(`https://wl-api.mf.gov.pl/api/search/nip/${encodeURIComponent(nip)}?date=${encodeURIComponent(date)}`);return{subject:j?.result?.subject||j?.result?.subjects?.[0]||null,requestId:j?.result?.requestId||'',requestDateTime:j?.result?.requestDateTime||''}}
async function whiteListBank(nip,account,date){account=digits(account);if(!/^\d{10}$/.test(nip)||!/^\d{26}$/.test(account)||!iso(date))return null;const j=await getJson(`https://wl-api.mf.gov.pl/api/check/nip/${encodeURIComponent(nip)}/bank-account/${encodeURIComponent(account)}?date=${encodeURIComponent(date)}`);return{assigned:clean(j?.result?.accountAssigned),requestId:j?.result?.requestId||'',requestDateTime:j?.result?.requestDateTime||''}}
async function nbpRate(currency,referenceDate){currency=clean(currency).toUpperCase();if(currency==='PLN'||!/^[A-Z]{3}$/.test(currency)||!iso(referenceDate))return null;const end=dateShift(referenceDate,-1),start=dateShift(referenceDate,-14);for(const table of ['a','b']){try{const j=await getJson(`https://api.nbp.pl/api/exchangerates/rates/${table}/${currency.toLowerCase()}/${start}/${end}/?format=json`),rates=Array.isArray(j?.rates)?j.rates:[];if(rates.length){const x=rates[rates.length-1];return{currency,table:table.toUpperCase(),date:x.effectiveDate,mid:Number(x.mid),no:x.no||'',manualUrl:table==='a'?'https://nbp.pl/statystyka-i-sprawozdawczosc/kursy/archiwum-kursow-srednich-tabela-a/':'https://nbp.pl/statystyka-i-sprawozdawczosc/kursy/archiwum-kursow-srednich-tabela-b/'}}}catch(e){if(!/404/.test(String(e.message)))throw e}}throw new Error(`NBP nie zwrócił średniego kursu ${currency} przed ${referenceDate}`)}
function xmlTag(xml,tag){const m=xml.match(new RegExp(`<(?:\\w+:)?${tag}[^>]*>([\\s\\S]*?)<\\/(?:\\w+:)?${tag}>`,'i'));return m?m[1].replace(/<[^>]+>/g,'').trim():''}
async function viesCheck(code,vat){code=clean(code).toUpperCase();if(code==='GR')code='EL';vat=clean(vat).replace(/[\s.\-]/g,'').replace(new RegExp(`^${code}`,'i'),'');if(!code||!vat)throw new Error('Nieprawidłowy numer VAT UE.');const body=`<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:ec.europa.eu:taxud:vies:services:checkVat:types"><soapenv:Header/><soapenv:Body><urn:checkVat><urn:countryCode>${code}</urn:countryCode><urn:vatNumber>${vat}</urn:vatNumber></urn:checkVat></soapenv:Body></soapenv:Envelope>`;let r;try{r=await nativeFetch('https://ec.europa.eu/taxation_customs/vies/services/checkVatService',{method:'POST',headers:{'Content-Type':'text/xml; charset=utf-8'},body})}catch{throw new Error('Przeglądarka zablokowała bezpośrednie połączenie VIES (CORS). Sprawdź numer ręcznie w VIES.')}if(!r.ok)throw new Error(`VIES HTTP ${r.status}`);const t=await r.text(),v=xmlTag(t,'valid');if(!v)throw new Error('VIES zwrócił odpowiedź bez pola valid');return{countryCode:code,vatNumber:vat,valid:v.toLowerCase()==='true',name:xmlTag(t,'name'),address:xmlTag(t,'address'),requestDate:xmlTag(t,'requestDate')}}
async function toolboxContractor(nip,date,country='',vat=''){nip=digits(nip);if(!/^\d{10}$/.test(nip)||!iso(date))throw new Error('Nieprawidłowy NIP lub data.');let r;try{r=await whiteListSearch(nip,date)}catch{throw new Error('Przeglądarka lub sieć firmowa zablokowała bezpośrednie API Białej Listy MF (CORS). Użyj oficjalnej strony MF albo wersji z backendem.')}const s=r?.subject||null,mf=s?{found:true,name:clean(s.name),statusVat:clean(s.statusVat),residenceAddress:clean(s.residenceAddress),workingAddress:clean(s.workingAddress),accountNumbers:Array.isArray(s.accountNumbers)?s.accountNumbers:[],krs:clean(s.krs),regon:clean(s.regon),registrationLegalDate:clean(s.registrationLegalDate),hasVirtualAccounts:!!s.hasVirtualAccounts}:{found:false,accountNumbers:[]};let vies=null,viesError='';if(clean(country)&&clean(vat)){try{vies=await viesCheck(country,vat)}catch(e){viesError=e.message||String(e)}}return{mf,vies,viesError,requestId:r?.requestId||'',requestDateTime:r?.requestDateTime||'',date}}
const TAX_RATE=[{from:'2022-02-09',rate:8.5},{from:'2022-03-09',rate:10},{from:'2022-04-07',rate:12},{from:'2022-05-06',rate:13.5},{from:'2022-06-09',rate:15},{from:'2022-07-08',rate:16},{from:'2022-09-08',rate:16.5},{from:'2023-09-07',rate:15},{from:'2023-10-05',rate:14.5},{from:'2025-05-08',rate:13.5},{from:'2025-07-03',rate:13},{from:'2025-09-04',rate:12.5},{from:'2025-10-09',rate:12},{from:'2025-11-06',rate:11.5},{from:'2025-12-04',rate:11},{from:'2026-03-05',rate:10.5}];
const TRADE=[{from:'2025-07-01',to:'2025-12-31',standard:15.25,medical:13.25,sourceName:'M.P. 2025 poz. 602',sourceUrl:'https://eli.gov.pl/eli/MP/2025/602/ogl'},{from:'2026-01-01',to:'2026-06-30',standard:14,medical:12,sourceName:'M.P. 2025 poz. 1257',sourceUrl:'https://eli.gov.pl/eli/MP/2025/1257/ogl'},{from:'2026-07-01',to:'2026-12-31',standard:13.75,medical:11.75,sourceName:'M.P. 2026 poz. 642',sourceUrl:'https://eli.gov.pl/eli/MP/2026/642/ogl'}];
const ZUS_URL='https://www.zus.pl/en/baza-wiedzy/skladki-wskazniki-odsetki/odsetki/wysokosc-stawek-odsetek-podatkowych-za-zwloke-od-nieterminowo-regulowanych-skladek-na-ubezpieczenia-spoleczne';
function dObj(s){return new Date(`${s}T00:00:00Z`)}function days(a,b){return Math.floor((dObj(b)-dObj(a))/86400000)+1}function addDay(s,n){const d=dObj(s);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function interest(type,amount,due,paid){amount=Number(amount);if(!Number.isFinite(amount)||amount<=0||!iso(due)||!iso(paid))throw new Error('Nieprawidłowa kwota lub data.');if(paid<=due)return{type,days:0,interest:0,total:round2(amount),segments:[],liveVerified:false,note:'Data zapłaty nie jest późniejsza niż termin płatności.'};const start=addDay(due,1),end=paid,isTax=String(type).startsWith('tax'),segments=[];if(isTax){const factor=type==='taxReduced'?.5:type==='taxIncreased'?1.5:1,cuts=[start,...TAX_RATE.map(x=>x.from).filter(x=>x>start&&x<=end)].sort();for(let i=0;i<cuts.length;i++){const from=cuts[i],to=i+1<cuts.length?addDay(cuts[i+1],-1):end,x=[...TAX_RATE].reverse().find(z=>z.from<=from);if(!x)continue;segments.push({from,to,days:days(from,to),rate:round2(x.rate*factor),sourceName:'ZUS — tabela stawek (wbudowana)',sourceUrl:ZUS_URL})}}else{const med=type==='tradeMedical',cuts=[start,...TRADE.map(x=>x.from).filter(x=>x>start&&x<=end)].sort();for(let i=0;i<cuts.length;i++){const from=cuts[i],to=i+1<cuts.length?addDay(cuts[i+1],-1):end,x=TRADE.find(z=>z.from<=from&&z.to>=from);if(!x)throw new Error('W trybie WORK brak wbudowanej stawki dla tego okresu.');segments.push({from,to,days:days(from,to),rate:med?x.medical:x.standard,sourceName:x.sourceName,sourceUrl:x.sourceUrl})}}let raw=0;for(const x of segments){x.interest=round2(amount*x.rate/100*x.days/365);raw+=amount*x.rate/100*x.days/365}const val=isTax?Math.round(raw):round2(raw);return{type,days:days(start,end),interest:val,total:round2(amount+val),segments,liveVerified:false,note:'Tryb WORK: stawki są z wbudowanej tabeli wersji 2.5.1; przed użyciem produkcyjnym potwierdź aktualność w podanym źródle urzędowym.'}}
function add(C,type,category,title,desc,field='',fix=''){C.push({type,category,title,desc,field,fix})}
async function audit(payload){const C=[],details={seller:{},buyer:{},bankAccounts:[],registryDate:''};let unavailable=0;const date=iso(payload?.invoiceDate)?payload.invoiceDate:new Date().toISOString().slice(0,10),seller={...(payload?.seller||{}),nip:digits(payload?.seller?.nip)},buyer={...(payload?.buyer||{}),nip:digits(payload?.buyer?.nip)};details.registryDate=date;for(const [key,label,p] of [['seller','sprzedawca',seller],['buyer','nabywca',buyer]]){if(/^\d{10}$/.test(p.nip)){try{const r=await whiteListSearch(p.nip,date),s=r?.subject;details[key].mf={found:!!s,registryDate:date,requestId:r?.requestId||'',name:s?.name||'',statusVat:s?.statusVat||'',residenceAddress:s?.residenceAddress||'',workingAddress:s?.workingAddress||'',accountNumbers:s?.accountNumbers||[]};if(s)add(C,clean(s.statusVat).toLowerCase()==='czynny'?'ok':'warn','registry',`Biała Lista MF — ${label}`,`NIP ${p.nip}: status VAT „${clean(s.statusVat)||'brak'}”.`,`NIP ${p.nip}`);else add(C,'warn','registry',`Biała Lista MF — ${label}`,`Nie znaleziono podmiotu dla NIP ${p.nip} na dzień ${date}.`,`NIP ${p.nip}`)}catch(e){unavailable++;add(C,'info','registry',`Biała Lista MF — ${label}`,`Bezpośrednie API MF niedostępne w tej przeglądarce: ${e.message}.`,`NIP ${p.nip}`,'Sprawdź ręcznie w oficjalnym wykazie MF.')}}}
if(Array.isArray(payload?.banks)&&payload.banks.length&&/^\d{10}$/.test(seller.nip)){for(const raw of payload.banks){const acc=digits(raw);if(!/^\d{26}$/.test(acc)){add(C,'warn','registry','Rachunek bankowy — format',`Rachunek „${raw}” nie ma 26 cyfr.`,raw);continue}try{const r=await whiteListBank(seller.nip,acc,date),yes=clean(r?.assigned).toUpperCase()==='TAK';details.bankAccounts.push({account:acc,assigned:yes,date,requestId:r?.requestId||''});add(C,yes?'ok':'warn','registry','Rachunek bankowy na Białej Liście',`${acc}: ${yes?'rachunek przypisany':'rachunek NIE został potwierdzony'} do NIP sprzedawcy na dzień ${date}.`,'Rachunek bankowy')}catch(e){unavailable++;add(C,'info','registry','Rachunek bankowy na Białej Liście',`Bezpośrednie API MF niedostępne: ${e.message}.`,'Rachunek bankowy')}}}
const currency=clean(payload?.currency).toUpperCase();if(currency&&currency!=='PLN'&&payload?.domesticVat&&!payload?.flags?.correction){const ref=iso(payload?.saleDate)?payload.saleDate:payload.invoiceDate;if(ref)try{const r=await nbpRate(currency,ref);add(C,'ok','fx','Kurs NBP — kurs referencyjny',`${currency}: średni kurs NBP ${r.mid.toFixed(4)} z ${r.date}, tabela ${r.table}${r.no?` ${r.no}`:''}.`,'Waluta')}catch(e){unavailable++;add(C,'info','fx','Kurs NBP',`Nie udało się pobrać kursu: ${e.message}.`,'Waluta')}}
return{checks:C,unavailable,details,checkedAt:new Date().toISOString(),registryDate:date}}
const legal=[{id:'fa3',name:'KSeF / FA(3)',url:'https://ksef.podatki.gov.pl/informacje-ogolne-ksef-20/struktura-logiczna-fa-3/'},{id:'scale',name:'podatki.gov.pl / skala',url:'https://www.podatki.gov.pl/podatki-firmowe/pit/stawki-i-limity'},{id:'linear',name:'podatki.gov.pl / liniowy',url:'https://www.podatki.gov.pl/podatki-firmowe/pit/informacje-podstawowe/co-jest-opodatkowane/opodatkowanie-podatkiem-liniowym'},{id:'health',name:'ZUS / zdrowotna',url:'https://www.zus.pl/pl/firmy/przedsiebiorco-przeczytaj-wazne/kalkulator-skladki-zdrowotnej'},{id:'assetHealth',name:'ZUS / sprzedaż ŚT',url:'https://www.zus.pl/en/-/od-1-maja-2026-r.-obowi%C4%85zuj%C4%85-nowe-wzory-formularzy-zus-dra-i-zus-rca'},{id:'mpp',name:'podatki.gov.pl / MPP',url:'https://www.podatki.gov.pl/podatki-firmowe/vat/poradniki-i-informatory/mechanizm-podzielonej-platnosci-mpp'},{id:'nbp',name:'NBP API',url:'https://api.nbp.pl/'}];
async function api(url,opts={}){const u=new URL(typeof url==='string'?url:url.url,location.href),path=u.pathname;if(!path.startsWith('/api/'))return nativeFetch(url,opts);try{
 if(path==='/api/pdf/extract'){const p=JSON.parse(opts.body||'{}');return json(await extractPdfPayload(p))}
 if(path==='/api/audit')return json(await audit(JSON.parse(opts.body||'{}')))
 if(path==='/api/xsd/validate')return json({available:false,ok:null,errors:[{message:'Tryb WORK: pełna walidacja XSD wymaga backendu lub osobnego silnika XSD.'}],engine:'WORK / browser'})
 if(path==='/api/xsd/status')return json({available:false,mode:'work',message:'Pełny XSD wyłączony w wersji statycznej.'})
 if(path==='/api/news'){const r=await nativeFetch('news_seed.json',{cache:'no-store'}),seed=await r.json();return json({version:'2.5.1-WORK',updatedAt:seed.generatedAt||new Date().toISOString(),articles:seed.articles||[],sources:[],freshSources:0,fallback:true})}
 if(path==='/api/health')return json({ok:true,version:'2.5.1-WORK',pdfParserInstalled:!!(window.pdfjsLib||window.PDFJS),pdfRendererInstalled:!!(window.pdfjsLib||window.PDFJS)})
 if(path==='/api/qa/server')return json({version:'2.5.1-WORK',platform:'browser',node:'nie dotyczy',files:[],xsd:{available:false},pdfParserInstalled:!!(window.pdfjsLib||window.PDFJS),pdfRendererInstalled:!!(window.pdfjsLib||window.PDFJS),excelInstalled:!!window.ExcelJS,time:new Date().toISOString()})
 if(path==='/api/toolbox/contractor')return json(await toolboxContractor(u.searchParams.get('nip')||'',u.searchParams.get('date')||'',u.searchParams.get('country')||'',u.searchParams.get('vat')||''))
 if(path==='/api/toolbox/bank'){const nip=digits(u.searchParams.get('nip')),account=digits(u.searchParams.get('account')),date=u.searchParams.get('date')||'';let r;try{r=await whiteListBank(nip,account,date)}catch{throw new Error('Przeglądarka lub sieć firmowa zablokowała API Białej Listy MF (CORS).')}return json({assigned:clean(r?.assigned).toUpperCase()==='TAK',requestId:r?.requestId||'',requestDateTime:r?.requestDateTime||'',nip,account,date})}
 if(path==='/api/toolbox/vies')return json(await viesCheck(u.searchParams.get('country')||'',u.searchParams.get('vat')||''))
 if(path==='/api/toolbox/nbp')return json(await nbpRate(u.searchParams.get('currency')||'',u.searchParams.get('date')||''))
 if(path==='/api/toolbox/interest')return json(interest(u.searchParams.get('type')||'',u.searchParams.get('amount')||'',u.searchParams.get('due')||'',u.searchParams.get('paid')||''))
 if(path==='/api/legal/status')return json({checkedAt:new Date().toISOString(),sources:legal.map(x=>({...x,ok:null,status:0,error:'Tryb WORK: link dostępny do ręcznej weryfikacji; automatyczne sprawdzanie źródła wyłączone.'}))})
 return json({error:'Ta funkcja serwerowa nie jest dostępna w statycznej wersji WORK.'},503)
 }catch(e){return json({error:e?.message||String(e)},503)}}
window.fetch=api;
window.ksefWork={mode:true,nativeFetch,extractPdfPayload,whiteListSearch,whiteListBank,nbpRate,viesCheck};
document.addEventListener('DOMContentLoaded',()=>{const note=document.createElement('div');note.className='work-mode-banner';note.innerHTML='<b>WORK / WEB</b><span>Tryb bez Node. XML i PDF są analizowane w przeglądarce. Do oficjalnych API mogą być wysyłane wyłącznie dane potrzebne do sprawdzenia (np. NIP, rachunek, waluta/data). Pełna walidacja XSD jest wyłączona.</span>';document.body.prepend(note)});
})();
